In [1]:
import pandas as pd
from IPython.display import display

In [2]:
tmp = pd.read_parquet("/opt/rws/repos/RWS_LightGBM/data/reprocessed/final_merged_with_spy/ml_ready_with_targets/AAPL.parquet")
pd.options.display.max_columns = None
display(tmp)

,timestamp,m5_rrs_rrs_spy,m5_rrs_rrs_sector,m5_mom_lrsi,m5_mom_tsi,m5_mom_squeeze_on,m5_vol_rel_vol,m5_vol_rel_cum_vol,m5_levels_chg_from_yest_close_pct,m5_levels_chg_from_open_pct,m5_ha_ha_color,ticker,spy_m5_rel_vol,spy_m5_rel_cum_vol,spy_m5_chg_from_yest_close_pct,spy_m5_chg_from_open_pct,spy_m5_lrsi,spy_m5_tsi,spy_m5_squeeze_on,spy_d1_atr_14,d1_trend_atr_14,d1_rrs_rrs_spy_5,d1_rrs_rrs_spy_5_sma,d1_rrs_rrs_sec_5,d1_rrs_rrs_sec_5_sma,d1_rrs_rrs_spy_12,d1_rrs_rrs_spy_12_sma,d1_rrs_rrs_sec_12,d1_rrs_rrs_sec_12_sma,d1_rrs_rrs_spy_25,d1_rrs_rrs_spy_25_sma,d1_rrs_rrs_sec_25,d1_rrs_rrs_sec_25_sma,d1_ha_ha_color,d1_lrsi_laguerre_rsi_0.7,d1_adx_adx,d1_adx_plus_di,d1_adx_minus_di,ticker_d1,time_weekday,time_sin,time_cos,month_sin,month_cos,dist_m5_ma_ema_3,dist_m5_ma_ema_8,dist_m5_ma_vwap,dist_m5_levels_yest_high,dist_m5_levels_yest_low,dist_m5_levels_yest_close,dist_m5_levels_hod,dist_m5_levels_lod,dist_m5_levels_session_open,dist_m5_ha_ha_open,dist_m5_ha_ha_high,dist_m5_ha_ha_low,dist_m5_ha_ha_close,dist_d1_trend_sma_20,dist_d1_trend_sma_50,dist_d1_trend_sma_100,dist_d1_trend_sma_200,dist_d1_trend_ema_8,dist_d1_trend_ema_21,dist_d1_trend_high_52w,dist_d1_trend_low_52w,dist_d1_trend_prev_day_high,dist_d1_trend_prev_day_low,dist_d1_trend_prev_week_high,dist_d1_trend_prev_week_low,dist_d1_trend_prev_month_high,dist_d1_trend_prev_month_low,dist_d1_ha_ha_open,dist_d1_ha_ha_high,dist_d1_ha_ha_low,dist_d1_ha_ha_close,dist_open_d1,dist_high_d1,dist_low_d1,dist_close_d1,dist_spy_m5_yest_high,dist_spy_m5_yest_low,dist_spy_m5_yest_close,dist_spy_m5_hod,dist_spy_m5_lod,dist_spy_m5_session_open,dist_spy_m5_ema_8,dist_spy_m5_vwap,dist_spy_d1_sma_20,dist_spy_d1_sma_50,dist_spy_d1_sma_200,dist_spy_d1_ema_8,dist_spy_d1_ema_21,dist_spy_d1_high_52w,dist_spy_d1_low_52w,dist_spy_d1_prev_day_high,dist_spy_d1_prev_day_low,d1_natr,target_reg_5m_logret,target_cls_5m,target_reg_30m_logret,target_cls_30m,target_reg_1h_logret,target_cls_1h,target_reg_2h_logret,target_cls_2h,target_reg_4h_logret,target_cls_4h,target_reg_1d_logret,target_cls_1d,target_reg_3d_logret,target_cls_3d,target_reg_5d_logret,target_cls_5d,target_reg_10d_logret,target_cls_10d
0,2000-01-04 09:30:00,NaN,NaN,0.446703,10.549690,0.0,1.000000,1.000000,-0.032920,0.000000,-1,AAPL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,NaN,NaN,NaN,AAPL,1,0.608761,-0.793353,0.000000e+00,1.0,0.014950,0.018381,0.000207,0.039317,-0.060631,0.034040,0.000621,-1.628104e-08,-1.628104e-08,0.028139,0.028139,-1.628104e-08,0.000155,NaN,NaN,NaN,NaN,0.034040,0.034040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.001449,0.039317,-0.060631,-0.004604,-0.031143,0.039317,-0.060631,0.034040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.006908,1.0,0.013769,1.0,0.002377,1.0,-0.018062,1.0,-0.022179,1.0,-0.054867,1.0,-0.107144,1.0,-0.083022,1.0,-0.033456,1.0
1,2000-01-04 09:35:00,1.334452,-0.322855,0.499058,7.310046,0.0,1.000000,1.000000,-0.026216,0.006932,-1,AAPL,1.000000,1.000000,NaN,-0.019182,0.985542,14.222584,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,NaN,NaN,NaN,AAPL,1,0.591310,-0.806445,0.000000e+00,1.0,0.003982,0.008843,-0.001767,0.032162,-0.067098,0.026922,0.005754,-6.884521e-03,-6.884521e-03,0.007165,0.007165,-6.884521e-03,-0.001850,NaN,NaN,NaN,NaN,0.026922,0.026922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.005446,0.032162,-0.067098,-0.011457,-0.037813,0.032162,-0.067098,0.026921,NaN,NaN,NaN,0.020394,-0.009719,0.020394,-0.000775,0.0,NaN,NaN,NaN,0.000820,0.000820,NaN,NaN,NaN,NaN,NaN,0.009104,1.0,0.003488,1.0,-0.009187,1.0,-0.027924,1.0,-0.027924,1.0,-0.049931,1.0,-0.128904,1.0,-0.107624,1.0,-0.038013,1.0
2,2000-01-04 09:40:00,2.054531,0.436295,0.672742,6.446432,0.0,1.000000,1.000000,-0.017310,0.016141,1,AAPL,1.000000,1.000000,-0.011820,0.001089,0.479557,1.785008,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,NaN,NaN,NaN,AAPL,1,0.573576,-0.819152,0.000000e+00,1.0,-0.002558,-0.000233,-0.007392,0.022808,-0.075552,0.017615,0.002342,-1.588435e-02,-1.588435e-02,-0.006429,0.002342,-1.354240e-02,-0.005066,NaN,NaN,NaN,NaN,0.017615,0.017615,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.014459,0.022808,-0.075552,-0.020415,-0.046533,0.022808,-0.075552,0.017615,0.032202,0.001741,0.012402,0.000435,-0.000870,-0.000653,0.008488,0.0,NaN,NaN,NaN,0.012402,0.012402,NaN,NaN,NaN,NaN,NaN,0.002339,1.0,-0.010234,1.0,-0.017151,1.0,-0.038191,1.0,-0.037028,1.0,-0.062064,1.0,-0.146577,1.0,-0.115469,1.0,-0.048291,1.0
3,2000-01-04 09:45:00,4.827221,1.359266,0.750550,6.183774,0.0,1.000000,1.000000,-0.015009,0.018520,1,AAPL,1.000000,1.000000,-0.013969,-0.001089,0.435599,-8.429669,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,NaN,NaN,NaN,AAPL,1,0.555570,-0.831470,0.000000e+00,1.0,-0.002444,-0.001998,-0.006167,0.020419,-0.077712,0.015238,0.001117,-1.818368e-02,-1.818368e-02,-0.008070,0.001117,-8.070085e-03,-0.001016,NaN,NaN,NaN,NaN,0.015238,0.015238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.016762,0.020419,-0.077712,-0.022704,-0.048761,0.020419,-0.077712,0.015238,0.032577,0.002104,0.012770,0.001451,-0.002466,-0.000290,0.006580,0.0,NaN,NaN,NaN,0.012770,0.012770,NaN,NaN,NaN,NaN,NaN,-0.002848,1.0,-0.017730,1.0,-0.020111,1.0,-0.030530,1.0,-0.038733,1.0,-0.058354,1.0,-0.133241,1.0,-0.122965,1.0,-0.040530,1.0
4,2000-01-04 09:50:00,2.031576,0.398978,0.667453,5.470725,0.0,1.000000,1.000000,-0.017811,0.015623,1,AAPL,1.000000,1.000000,-0.012680,0.000218,0.445078,-14.098132,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,NaN,NaN,NaN,AAPL,1,0.537300,-0.843391,0.000000e+00,1.0,0.000201,0.000660,-0.002153,0.023329,-0.075082,0.018134,0.006214,-1.538306e-02,-1.538306e-02,-0.001703,0.006214,-1.731864e-03,0.001961,NaN,NaN,NaN,NaN,0.018134,0.018134,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.013957,0.023329,-0.075082,-0.019916,-0.046047,0.023329,-0.075081,0.018134,0.032655,0.002180,0.012846,0.001527,-0.002391,-0.000214,0.005178,0.0,NaN,NaN,NaN,0.012846,0.012846,NaN,NaN,NaN,NaN,NaN,-0.000611,1.0,-0.021314,1.0,-0.025381,1.0,-0.025903,1.0,-0.032932,1.0,-0.041179,1.0,-0.115646,1.0,-0.116905,1.0,-0.042453,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
506901,2025-07-25 15:40:00,-2.464130,-1.714512,0.000000,-24.447796,0.0,0.671053,0.729836,-0.001986,-0.004822,-1,AAPL,0.607204,0.722762,0.004698,0.003559,0.917999,21.574320,1.0,4.440928,3.391807,-0.373532,-0.389489,0.931987,0.066977,-1.849678,-0.993798,-0.631126,-0.878362,-1.952338,-2.595347,-1.29387,-3.76959,1.0,1.0,19.538063,23.862541,12.367239,AAPL,4,-0.819152,-0.573576,1.224647e-16,-1.0,0.000006,0.000324,0.003111,0.009761,-0.000351,0.001990,0.007654,-9.597439e-04,4.845389e-03,0.000085,0.000533,-3.043314e-04,0.000004,-0.016985,-0.038599,-0.026845,0.039644,-0.004967,-0.018261,0.217668,-0.207836,0.007233,-0.005594,0.012289,-0.029892,0.004471,-0.095293,-0.000361,0.009761,-0.000361,0.003195,0.001381,0.009761,-0.000351,0.001990,-0.000311,-0.003706,-0.003156,0.001936,-0.002370,-0.002024,0.001600,0.0,-0.020021,-0.047411,-0.078022,-0.011099,-0.022766,-0.000311,-0.242867,-0.001490,-0.010400,0.015879,0.000234,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506902,2025-07-25 15:45:00,-0.694691,0.567076,0.000000,-23.630857,0.0,0.647920,0.728836,-0.001752,-0.004589,1,AAPL,0.908817,0.726364,0.004911,0.003771,1.000000,21.460234,1.0,4.440928,3.391807,-0.373532,-0.389489,0.931987,0.066977,-1.849678,-0.993798,-0.631126,-0.878362,-1.952338,-2.595347,-1.29387,-3.76959,1.0,1.0,19.538063,23.862541,12.367239,AAPL,4,-0.831470,-0.555570,1.224647e-16,-1.0,-0.000114,0.000070,0.002844,0.009525,-0.000585,0.001755,0.007419,-1.193541e-03,4.610233e-03,-0.000189,0.000257,-4.914322e-04,-0.000117,-0.017215,-0.038824,-0.027072,0.039401,-0.005199,-0.018491,0.217383,-0.208022,0.006997,-0.005827,0.012052,-0.030119,0.004236,-0.095504,-0.000595,0.009525,-0.000595,0.002960,0.001147,0.009525,-0.000585,0.001755,-0.000352,-0.003747,-0.003197,0.001895,-0.002411,-0.002065,0.001590,0.0,-0.020061,-0.047450,-0.078059,-0.011139,-0.022806,-0.000352,-0.242898,-0.001531,-0.010441,0.015875,0.000866,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506903,2025-07-25 15:50:00,-0.038266,0.602122,0.072546,-20.160181,0.0,0.777304,0.729694,-0.000888,-0.003727,1,AAPL,0.846949,0.728845,0.004682,0.003543,0.902754,19.143709,1.0,4.440928,3.391807,-0.373532,-0.389489,0.931987,0.066977,-1.849678,-0.993798,-0.631126,-0.878362,-1.952338,-2.595347,-1.29387,-3.76959,1.0,1.0,19.538063,23.862541,12.367239,AAPL,4,-0.843391,-0.537300,1.224647e-16,-1.0,-0.000490,-0.000619,0.001934,0.008651,-0.001450,0.000889,0.006547,-2.057642e-03,3.741112e-03,-0.001018,0.000070,-1.018197e-03,-0.000415,-0.018065,-0.039656,-0.027914,0.038501,-0.006060,-0.019340,0.216330,-0.208707,0.006126,-0.006687,0.011177,-0.030958,0.003367,-0.096287,-0.001460,0.008651,-0.001460,0.002093,0.000281,0.008651,-0.001450,0.000889,-0.000388,-0.003782,-0.003232,0.001859,-0.002447,-0.002101,0.001527,0.0,-0.020096,-0.047484,-0.078093,-0.011174,-0.022841,-0.000388,-0.242925,-0.001567,-0.010476,0.015861,0.000164,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506904,2025-07-25 15:55:00,2.248333,3.229520,0.218703,-16.932796,0.0,0.723775,0.729508,-0.000724,-0.003564,1,AAPL,0.684967,0.727525,0.004493,0.003354,0.586184,15.525219,1.0,4.440928,3.391807,-0.373532,-0.389489,0.931987,0.066977,-1.849678,-0.993798,-0.631126,-0.878362,-1.952338,-2.595347,-1.29387,-3.76959,1.0,1.0,19.538063,23.862541,12.367239,AAPL,4,-0.854912,-0.518773,1.224647e-16,-1.0,-0.000327,-0.000608,0.001708,0.008486,-0.001613,0.000725,0.006382,-2.220952e-03,3.576853e-03,-0.000880,0.000468,-1.145506e-03,-0.000205,-0.018226,-0.039813,-0.028073,0.038332,-0.006223,-0.019500,0.216131,-0.208836,0.005961,-0.006850,0.011011,-0.031116,0.003203,-0.096435,-0.001623,0.008486,-0.001623,0.001929,0.000117,0.008486,-0.001613,0.000725,-0.000425,-0.003819,-0.003269,0.001821,-0.002484,-0.002138,0.001427,0.0,-0.020133,-0.047520,-0.078127,-0.011211,-0.022878,-0.000425,-0.242954,-0.001604,-0.010513,0.015859,-0.000631,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506905,2025-07-25 16:00:00,0.876029,3.214252,0.153542,-15.778984,1.0,0.589343,0.696608,-0.001355,-0.004193,1,AAPL,1.162845,0.746520,0.003862,0.002724,0.379329,7.227488,0.0,4.440928,3.391807,-0.373532,-0.389489,0.931987,0.066977,-1.849678,-0.993798,-0.631126,-0.878362,-1.952338,-2.595347,-1.29387,-3.76959,1.0,1.0,19.538063,23.862541,12.367239,AAPL,4,-0.866025,-0.500000,1.224647e-16,-1.0,0.000152,0.000018,0.001953,0.009123,-0.000983,0.001357,0.007018,-1.590746e-03,4.210720e-03,0.000089,0.001216,-4.680580e-05,0.000444,-0.017606,-0.039206,-0.027459,0.038987,-0.005595,-0.018881,0.216899,-0.208337,0.006597,-0.006222,0.011650,-0.030504,0.003836,-0.095864,-0.000993,0.009123,-0.000993,0.002562,0.000749,0.009123,-0.000983,0.001357,-0.000474,-0.003867,-0.003317,0.001773,-0.002532,-0.002186,0.001191,0.0,-0.020180,-0.047566,-0.078171,-0.011259,-0.022925,-0.000474,-0.242990,-0.001652,-0.010561,0.015869,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
pd.set_option('display.max_rows', None)
display(tmp.describe().T)

,count,mean,min,25%,50%,75%,max,std
timestamp,506906,2012-10-17 23:12:00.520569,2000-01-04 09:30:00,2006-06-01 15:41:15,2012-10-16 12:47:30,2019-03-08 11:33:45,2025-07-25 16:00:00,NaN
m5_rrs_rrs_spy,506447.0,0.023114,-21.756632,-1.154561,-0.008291,1.145878,29.894161,2.150877
m5_rrs_rrs_sector,497370.0,0.02325,-18.964575,-1.045719,-0.008507,1.041861,19.256159,1.978894
m5_mom_lrsi,506906.0,0.516153,0.0,0.110233,0.532128,0.937693,1.0,0.387427
m5_mom_tsi,506906.0,1.8034,-86.271149,-12.567369,1.412041,15.756638,86.43721,21.518599
m5_mom_squeeze_on,506906.0,0.242299,0.0,0.0,0.0,0.0,1.0,0.428475
m5_vol_rel_vol,506906.0,1.016199,0.000022,0.574928,0.817565,1.190132,65.585503,0.893539
m5_vol_rel_cum_vol,506906.0,1.008444,0.008352,0.698423,0.874278,1.137173,48.316849,0.654815
m5_levels_chg_from_yest_close_pct,506906.0,0.001205,-0.522191,-0.007704,0.001161,0.010377,0.169827,0.020566
m5_levels_chg_from_open_pct,506906.0,0.000454,-0.141869,-0.006698,0.000374,0.007666,0.162734,0.01514
m5_ha_ha_color,506906.0,0.01738,-1.0,-1.0,1.0,1.0,1.0,0.99985
spy_m5_rel_vol,506447.0,1.037089,0.00001,0.541369,0.811472,1.23967,58.86628,0.908435
spy_m5_rel_cum_vol,506447.0,1.023834,0.000157,0.743207,0.926181,1.182104,58.86628,0.466701
spy_m5_chg_from_yest_close_pct,506446.0,0.00023,-0.11137,-0.003649,0.000442,0.004567,0.111062,0.009353
spy_m5_chg_from_open_pct,506447.0,0.000038,-0.084186,-0.002746,0.000181,0.003028,0.104734,0.006715
spy_m5_lrsi,506447.0,0.531632,0.0,0.133978,0.559541,0.96084,1.0,0.38703
spy_m5_tsi,506447.0,2.159354,-81.704666,-12.497915,2.265992,16.830448,87.375809,21.652702
spy_m5_squeeze_on,506447.0,0.232619,0.0,0.0,0.0,0.0,1.0,0.422502
spy_d1_atr_14,505879.0,2.946424,0.74,1.456429,2.023571,3.5769,24.058571,2.41233
d1_trend_atr_14,505879.0,1.092478,0.006421,0.076579,0.348471,1.092321,13.846472,1.659423
d1_rrs_rrs_spy_5,506511.0,0.119032,-6.595678,-0.817343,0.053302,0.976991,8.596402,1.530655
d1_rrs_rrs_spy_5_sma,506195.0,0.119987,-4.976721,-0.653417,0.082388,0.862975,7.150587,1.26254
d1_rrs_rrs_sec_5,506511.0,0.101223,-5.137199,-0.677355,0.067164,0.843632,6.948868,1.29656
d1_rrs_rrs_sec_5_sma,506195.0,0.101414,-4.171329,-0.550283,0.069313,0.715291,5.798776,1.059982
d1_rrs_rrs_spy_12,505958.0,0.287943,-9.153005,-1.197067,0.270478,1.712066,10.056437,2.353643
d1_rrs_rrs_spy_12_sma,505089.0,0.288769,-6.193616,-0.876046,0.270563,1.518712,8.017786,1.913062
d1_rrs_rrs_sec_12,505958.0,0.244055,-7.038302,-0.991445,0.192676,1.41374,9.210276,1.93966
d1_rrs_rrs_sec_12_sma,505089.0,0.244813,-4.73657,-0.741039,0.221744,1.204581,6.783309,1.560186
d1_rrs_rrs_spy_25,504931.0,0.601223,-13.305948,-1.455565,0.64056,2.808871,12.583515,3.342995
d1_rrs_rrs_spy_25_sma,503035.0,0.601207,-8.965094,-1.048837,0.766056,2.438091,9.249664,2.726703
d1_rrs_rrs_sec_25,504931.0,0.51062,-9.558327,-1.29018,0.492722,2.193527,11.0252,2.770633
d1_rrs_rrs_sec_25_sma,503035.0,0.518344,-6.209555,-0.944396,0.517465,1.910856,8.275477,2.276949
d1_ha_ha_color,506906.0,0.125562,-1.0,-1.0,1.0,1.0,1.0,0.992087
d1_lrsi_laguerre_rsi_0.7,506906.0,0.602746,0.0,0.233685,0.704096,1.0,1.0,0.385097
d1_adx_adx,504852.0,26.833893,7.832256,18.492939,25.087152,32.888927,70.784233,10.722382
d1_adx_plus_di,505879.0,25.509027,4.720641,18.865564,24.72263,31.404911,61.373177,8.742121
d1_adx_minus_di,505879.0,22.121223,3.863365,16.08746,21.307682,27.462088,57.836189,8.124407
time_weekday,506906.0,2.022186,0.0,1.0,2.0,3.0,4.0,1.398888
time_sin,506906.0,-0.17109,-0.866025,-0.59131,-0.19509,0.237686,0.608761,0.453304
time_cos,506906.0,-0.864037,-1.0,-0.976296,-0.906308,-0.793353,-0.5,0.136692
month_sin,506906.0,0.009996,-1.0,-0.5,0.0,0.866025,1.0,0.708331
month_cos,506906.0,-0.012525,-1.0,-0.866025,-0.0,0.5,1.0,0.7057
dist_m5_ma_ema_3,506906.0,-0.000006,-0.058186,-0.000497,-0.000014,0.00048,0.444814,0.001727
dist_m5_ma_ema_8,506906.0,-0.000023,-0.092676,-0.001094,-0.000046,0.001024,0.689108,0.003635
dist_m5_ma_vwap,506906.0,-0.000014,-0.088739,-0.003345,-0.000099,0.003113,0.149668,0.007137
dist_m5_levels_yest_high,506906.0,0.012789,-0.130507,-0.00097,0.008846,0.022797,1.110013,0.027787
dist_m5_levels_yest_low,506906.0,-0.01464,-0.226928,-0.024924,-0.012425,-0.00235,0.887132,0.025676
dist_m5_levels_yest_close,506906.0,-0.000738,-0.145173,-0.010271,-0.00116,0.007764,1.092885,0.023547
dist_m5_levels_hod,506906.0,0.010288,-0.0,0.003043,0.006786,0.013511,0.230686,0.01127
dist_m5_levels_lod,506906.0,-0.010799,-0.197897,-0.014161,-0.007611,-0.003706,0.0,0.010889
dist_m5_levels_session_open,506906.0,-0.000225,-0.139958,-0.007608,-0.000374,0.006743,0.165323,0.015128
dist_m5_ha_ha_open,506906.0,-0.000017,-0.116468,-0.001142,-0.000036,0.001095,0.888913,0.003724
dist_m5_ha_ha_high,506906.0,0.001684,-0.0,0.000402,0.000968,0.002062,0.888913,0.002888
dist_m5_ha_ha_low,506906.0,-0.001718,-0.169786,-0.002106,-0.001024,-0.000447,0.0,0.002395
dist_m5_ha_ha_close,506906.0,-0.000004,-0.066392,-0.000454,-0.000006,0.000441,0.057399,0.001198
dist_d1_trend_sma_20,505405.0,-0.005427,-0.227032,-0.04522,-0.013618,0.02262,1.423612,0.078448
dist_d1_trend_sma_50,503035.0,-0.011817,-0.314065,-0.077719,-0.029249,0.025341,1.546963,0.129294
dist_d1_trend_sma_100,499086.0,-0.02169,-0.423101,-0.118592,-0.054349,0.02323,1.692119,0.192862
dist_d1_trend_sma_200,491227.0,-0.047626,-0.513,-0.178832,-0.105985,0.017552,2.343837,0.264857
dist_d1_trend_ema_8,506906.0,-0.002478,-0.188025,-0.023284,-0.006011,0.014118,1.106418,0.042076
dist_d1_trend_ema_21,506906.0,-0.005423,-0.206872,-0.041039,-0.013765,0.01952,1.258856,0.070088
dist_d1_trend_high_52w,487155.0,0.2473,-0.101978,0.034302,0.097026,0.253108,4.185786,0.450041
dist_d1_trend_low_52w,487155.0,-0.339629,-0.758495,-0.437628,-0.342059,-0.233859,0.115171,0.157191
dist_d1_trend_prev_day_high,506827.0,0.012254,-0.18236,-0.007231,0.007986,0.027022,1.283508,0.038619
dist_d1_trend_prev_day_low,506827.0,-0.015172,-0.265728,-0.030988,-0.014174,0.001383,1.0423,0.035855
dist_d1_trend_prev_week_high,506195.0,0.027568,-0.25634,-0.02258,0.014509,0.060397,1.847004,0.099422
dist_d1_trend_prev_week_low,506195.0,-0.041089,-0.291781,-0.082187,-0.042512,-0.004181,1.272588,0.075183
dist_d1_trend_prev_month_high,503825.0,0.052339,-0.493142,-0.075295,0.0045,0.102374,2.960913,0.25331
dist_d1_trend_prev_month_low,503825.0,-0.108899,-0.572051,-0.198184,-0.123619,-0.043306,1.669324,0.163124
dist_d1_ha_ha_open,506906.0,-0.001885,-0.20346,-0.021409,-0.004376,0.014886,1.186899,0.040298
dist_d1_ha_ha_high,506906.0,0.015993,-0.130507,0.000159,0.010533,0.026291,1.186899,0.034245
dist_d1_ha_ha_low,506906.0,-0.018652,-0.226928,-0.030202,-0.015968,-0.004393,0.887132,0.027573
dist_d1_ha_ha_close,506906.0,-0.000836,-0.161461,-0.011707,-0.00166,0.008985,1.005929,0.02478
dist_open_d1,506906.0,-0.000757,-0.221096,-0.015026,-0.001776,0.012382,0.933685,0.029603
dist_high_d1,506906.0,0.012789,-0.130507,-0.00097,0.008846,0.022797,1.110013,0.027787
dist_low_d1,506906.0,-0.01464,-0.226928,-0.024924,-0.012425,-0.00235,0.887132,0.025676
dist_close_d1,506906.0,-0.000738,-0.145173,-0.010271,-0.00116,0.007764,1.092885,0.023547
dist_spy_m5_yest_high,506446.0,0.006212,-0.04228,0.000151,0.003861,0.00996,0.168352,0.011021
dist_spy_m5_yest_low,506446.0,-0.006838,-0.144082,-0.010747,-0.005412,-0.001401,0.066337,0.010475
dist_spy_m5_yest_close,506446.0,-0.000066,-0.073871,-0.003629,-0.000298,0.003044,0.121713,0.007731
dist_spy_m5_hod,506447.0,0.004512,0.0,0.002144,0.003466,0.005587,0.070832,0.003895
dist_spy_m5_lod,506447.0,-0.004629,-0.084414,-0.005746,-0.003676,-0.002298,0.0,0.003922
dist_spy_m5_session_open,506447.0,0.000084,-0.058011,-0.001753,-0.000008,0.001807,0.04096,0.004122
dist_spy_m5_ema_8,506447.0,0.000086,-0.046265,-0.001168,0.000135,0.001416,0.072737,0.003057
dist_spy_m5_vwap,506447.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
dist_spy_d1_sma_20,504965.0,-0.001708,-0.106709,-0.018194,-0.007055,0.010035,0.331378,0.028351
dist_spy_d1_sma_50,502625.0,-0.004386,-0.130884,-0.03118,-0.013771,0.012344,0.421191,0.044322
dist_spy_d1_sma_200,490963.0,-0.016526,-0.171123,-0.071683,-0.040416,0.01351,0.64034,0.092052
dist_spy_d1_ema_8,506447.0,-0.000648,-0.074679,-0.009521,-0.003076,0.006046,0.20898,0.015678
dist_spy_d1_ema_21,506447.0,-0.001748,-0.072605,-0.016779,-0.0071,0.008442,0.307888,0.025132
dist_spy_d1_high_52w,486942.0,0.092667,-0.013981,0.00896,0.032688,0.114448,1.118943,0.145107
dist_spy_d1_low_52w,486942.0,-0.172801,-0.450714,-0.216311,-0.161571,-0.119544,0.066337,0.082459
dist_spy_d1_prev_day_high,506369.0,0.006047,-0.106099,-0.002805,0.003295,0.012268,0.186466,0.015881
dist_spy_d1_prev_day_low,506369.0,-0.006998,-0.204682,-0.013804,-0.006164,0.000612,0.124112,0.015354
d1_natr,505879.0,0.030061,0.008479,0.01867,0.025591,0.035325,0.263089,0.01822
target_reg_5m_logret,506905.0,0.000011,-0.636152,-0.000852,0.0,0.000869,0.123566,0.002931
target_cls_5m,506905.0,1.002326,0.0,1.0,1.0,1.0,2.0,0.547487
target_reg_30m_logret,506900.0,0.000064,-0.654064,-0.002105,0.000019,0.002228,0.135902,0.00681
target_cls_30m,506900.0,1.009081,0.0,1.0,1.0,1.0,2.0,0.552266
target_reg_1h_logret,506894.0,0.000128,-0.719189,-0.003029,0.000092,0.003277,0.141438,0.009559
target_cls_1h,506894.0,1.012975,0.0,1.0,1.0,1.0,2.0,0.562661
target_reg_2h_logret,506882.0,0.000256,-0.715615,-0.004489,0.000258,0.005081,0.163295,0.013425
target_cls_2h,506882.0,1.019454,0.0,1.0,1.0,1.0,2.0,0.585936
target_reg_4h_logret,506858.0,0.000512,-0.716872,-0.007016,0.000624,0.008332,0.187798,0.018951
target_cls_4h,506858.0,1.02991,0.0,1.0,1.0,1.0,2.0,0.622015
target_reg_1d_logret,506828.0,0.000833,-0.731339,-0.009656,0.001151,0.01179,0.206563,0.024168
target_cls_1d,506828.0,1.038838,0.0,1.0,1.0,1.0,2.0,0.650335
target_reg_3d_logret,506672.0,0.002512,-0.872263,-0.017078,0.003581,0.023526,0.253839,0.041494
target_cls_3d,506672.0,1.073774,0.0,1.0,1.0,2.0,2.0,0.675595
target_reg_5d_logret,506516.0,0.004207,-0.880211,-0.022113,0.006463,0.032356,0.304713,0.053801
target_cls_5d,506516.0,1.089535,0.0,1.0,1.0,2.0,2.0,0.686539
target_reg_10d_logret,506126.0,0.008446,-0.992141,-0.030029,0.012957,0.051674,0.318117,0.07797
target_cls_10d,506126.0,1.125139,0.0,1.0,1.0,2.0,2.0,0.704037

In [12]:
def foo(x):
    return (x - 50) / 25

foo(0)

-2.0

In [8]:
tmp.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506906 entries, 0 to 506905
Data columns (total 115 columns):
 #    Column                             Dtype
---   ------                             -----
 0    timestamp                          datetime64[us]
 1    m5_rrs_rrs_spy                     float32
 2    m5_rrs_rrs_sector                  float32
 3    m5_mom_lrsi                        float32
 4    m5_mom_tsi                         float32
 5    m5_mom_squeeze_on                  float32
 6    m5_vol_rel_vol                     float32
 7    m5_vol_rel_cum_vol                 float32
 8    m5_levels_chg_from_yest_close_pct  float32
 9    m5_levels_chg_from_open_pct        float32
 10   m5_ha_ha_color                     int8
 11   ticker                             object
 12   spy_m5_rel_vol                     float32
 13   spy_m5_rel_cum_vol                 float32
 14   spy_m5_chg_from_yest_close_pct     float32
 15   spy_m5_chg_from_open_pct           float32
 16   spy_m5_lrsi                        float32
 17   spy_m5_tsi                         float32
 18   spy_m5_squeeze_on                  float32
 19   spy_d1_atr_14                      float32
 20   d1_trend_atr_14                    float32
 21   d1_rrs_rrs_spy_5                   float32
 22   d1_rrs_rrs_spy_5_sma               float32
 23   d1_rrs_rrs_sec_5                   float32
 24   d1_rrs_rrs_sec_5_sma               float32
 25   d1_rrs_rrs_spy_12                  float32
 26   d1_rrs_rrs_spy_12_sma              float32
 27   d1_rrs_rrs_sec_12                  float32
 28   d1_rrs_rrs_sec_12_sma              float32
 29   d1_rrs_rrs_spy_25                  float32
 30   d1_rrs_rrs_spy_25_sma              float32
 31   d1_rrs_rrs_sec_25                  float32
 32   d1_rrs_rrs_sec_25_sma              float32
 33   d1_ha_ha_color                     float32
 34   d1_lrsi_laguerre_rsi_0.7           float32
 35   d1_adx_adx                         float32
 36   d1_adx_plus_di                     float32
 37   d1_adx_minus_di                    float32
 38   ticker_d1                          object
 39   time_weekday                       int8
 40   time_sin                           float32
 41   time_cos                           float32
 42   month_sin                          float32
 43   month_cos                          float32
 44   dist_m5_ma_ema_3                   float32
 45   dist_m5_ma_ema_8                   float32
 46   dist_m5_ma_vwap                    float32
 47   dist_m5_levels_yest_high           float32
 48   dist_m5_levels_yest_low            float32
 49   dist_m5_levels_yest_close          float32
 50   dist_m5_levels_hod                 float32
 51   dist_m5_levels_lod                 float32
 52   dist_m5_levels_session_open        float32
 53   dist_m5_ha_ha_open                 float32
 54   dist_m5_ha_ha_high                 float32
 55   dist_m5_ha_ha_low                  float32
 56   dist_m5_ha_ha_close                float32
 57   dist_d1_trend_sma_20               float32
 58   dist_d1_trend_sma_50               float32
 59   dist_d1_trend_sma_100              float32
 60   dist_d1_trend_sma_200              float32
 61   dist_d1_trend_ema_8                float32
 62   dist_d1_trend_ema_21               float32
 63   dist_d1_trend_high_52w             float32
 64   dist_d1_trend_low_52w              float32
 65   dist_d1_trend_prev_day_high        float32
 66   dist_d1_trend_prev_day_low         float32
 67   dist_d1_trend_prev_week_high       float32
 68   dist_d1_trend_prev_week_low        float32
 69   dist_d1_trend_prev_month_high      float32
 70   dist_d1_trend_prev_month_low       float32
 71   dist_d1_ha_ha_open                 float32
 72   dist_d1_ha_ha_high                 float32
 73   dist_d1_ha_ha_low                  float32
 74   dist_d1_ha_ha_close                float32
 75   dist_open_d1                       float32
 76   dist_high_d1                       float32
 77   dist_low_d1                        float32
 78   dist_close_d1                      float32
 79   dist_spy_m5_yest_high              float32
 80   dist_spy_m5_yest_low               float32
 81   dist_spy_m5_yest_close             float32
 82   dist_spy_m5_hod                    float32
 83   dist_spy_m5_lod                    float32
 84   dist_spy_m5_session_open           float32
 85   dist_spy_m5_ema_8                  float32
 86   dist_spy_m5_vwap                   float32
 87   dist_spy_d1_sma_20                 float32
 88   dist_spy_d1_sma_50                 float32
 89   dist_spy_d1_sma_200                float32
 90   dist_spy_d1_ema_8                  float32
 91   dist_spy_d1_ema_21                 float32
 92   dist_spy_d1_high_52w               float32
 93   dist_spy_d1_low_52w                float32
 94   dist_spy_d1_prev_day_high          float32
 95   dist_spy_d1_prev_day_low           float32
 96   d1_natr                            float32
 97   target_reg_5m_logret               float32
 98   target_cls_5m                      float32
 99   target_reg_30m_logret              float32
 100  target_cls_30m                     float32
 101  target_reg_1h_logret               float32
 102  target_cls_1h                      float32
 103  target_reg_2h_logret               float32
 104  target_cls_2h                      float32
 105  target_reg_4h_logret               float32
 106  target_cls_4h                      float32
 107  target_reg_1d_logret               float32
 108  target_cls_1d                      float32
 109  target_reg_3d_logret               float32
 110  target_cls_3d                      float32
 111  target_reg_5d_logret               float32
 112  target_cls_5d                      float32
 113  target_reg_10d_logret              float32
 114  target_cls_10d                     float32
dtypes: datetime64[us](1), float32(110), int8(2), object(2)
memory usage: 225.3+ MB

In [3]:
ohlcvAAPL = pd.read_parquet("/opt/rws/repos/RWS_LightGBM/data/reprocessed/stocks_m5_mdv_gt_100M/AAPL.parquet")
display(ohlcvAAPL)

                 timestamp      open      high       low     close    volume
0      2000-01-03 09:30:00    0.9364    0.9375    0.9364    0.9375   3662400
1      2000-01-03 09:35:00    0.9381    0.9408    0.9319    0.9325  20832000
2      2000-01-03 09:40:00    0.9325    0.9375    0.9219    0.9219   8344000
3      2000-01-03 09:45:00    0.9224    0.9369    0.9208    0.9358   9676800
4      2000-01-03 09:50:00    0.9369    0.9375    0.9314    0.9342  12196800
...                    ...       ...       ...       ...       ...       ...
506980 2025-07-25 15:40:00  213.5599  213.7188  213.5400  213.6050    231015
506981 2025-07-25 15:45:00  213.6050  213.7100  213.5500  213.6550    216541
506982 2025-07-25 15:50:00  213.6600  213.8550  213.6500  213.8400    383652
506983 2025-07-25 15:55:00  213.8450  213.9750  213.6300  213.8750    654265
506984 2025-07-25 16:00:00  213.8700  214.0000  213.7300  213.7400   5198826

[506985 rows x 6 columns]

In [9]:
ohlcvAAPL.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506985 entries, 0 to 506984
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   timestamp  506985 non-null  datetime64[us]
 1   open       506985 non-null  float64
 2   high       506985 non-null  float64
 3   low        506985 non-null  float64
 4   close      506985 non-null  float64
 5   volume     506985 non-null  int64
dtypes: datetime64[us](1), float64(4), int64(1)
memory usage: 23.2 MB

In [6]:
tmp.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506906 entries, 0 to 506905
Data columns (total 115 columns):
 #    Column                             Dtype
---   ------                             -----
 0    timestamp                          datetime64[us]
 1    m5_rrs_rrs_spy                     float32
 2    m5_rrs_rrs_sector                  float32
 3    m5_mom_lrsi                        float32
 4    m5_mom_tsi                         float32
 5    m5_mom_squeeze_on                  float32
 6    m5_vol_rel_vol                     float32
 7    m5_vol_rel_cum_vol                 float32
 8    m5_levels_chg_from_yest_close_pct  float32
 9    m5_levels_chg_from_open_pct        float32
 10   m5_ha_ha_color                     int8
 11   ticker                             object
 12   spy_m5_rel_vol                     float32
 13   spy_m5_rel_cum_vol                 float32
 14   spy_m5_chg_from_yest_close_pct     float32
 15   spy_m5_chg_from_open_pct           float32
 16   spy_m5_lrsi                        float32
 17   spy_m5_tsi                         float32
 18   spy_m5_squeeze_on                  float32
 19   spy_d1_atr_14                      float32
 20   d1_trend_atr_14                    float32
 21   d1_rrs_rrs_spy_5                   float32
 22   d1_rrs_rrs_spy_5_sma               float32
 23   d1_rrs_rrs_sec_5                   float32
 24   d1_rrs_rrs_sec_5_sma               float32
 25   d1_rrs_rrs_spy_12                  float32
 26   d1_rrs_rrs_spy_12_sma              float32
 27   d1_rrs_rrs_sec_12                  float32
 28   d1_rrs_rrs_sec_12_sma              float32
 29   d1_rrs_rrs_spy_25                  float32
 30   d1_rrs_rrs_spy_25_sma              float32
 31   d1_rrs_rrs_sec_25                  float32
 32   d1_rrs_rrs_sec_25_sma              float32
 33   d1_ha_ha_color                     float32
 34   d1_lrsi_laguerre_rsi_0.7           float32
 35   d1_adx_adx                         float32
 36   d1_adx_plus_di                     float32
 37   d1_adx_minus_di                    float32
 38   ticker_d1                          object
 39   time_weekday                       int8
 40   time_sin                           float32
 41   time_cos                           float32
 42   month_sin                          float32
 43   month_cos                          float32
 44   dist_m5_ma_ema_3                   float32
 45   dist_m5_ma_ema_8                   float32
 46   dist_m5_ma_vwap                    float32
 47   dist_m5_levels_yest_high           float32
 48   dist_m5_levels_yest_low            float32
 49   dist_m5_levels_yest_close          float32
 50   dist_m5_levels_hod                 float32
 51   dist_m5_levels_lod                 float32
 52   dist_m5_levels_session_open        float32
 53   dist_m5_ha_ha_open                 float32
 54   dist_m5_ha_ha_high                 float32
 55   dist_m5_ha_ha_low                  float32
 56   dist_m5_ha_ha_close                float32
 57   dist_d1_trend_sma_20               float32
 58   dist_d1_trend_sma_50               float32
 59   dist_d1_trend_sma_100              float32
 60   dist_d1_trend_sma_200              float32
 61   dist_d1_trend_ema_8                float32
 62   dist_d1_trend_ema_21               float32
 63   dist_d1_trend_high_52w             float32
 64   dist_d1_trend_low_52w              float32
 65   dist_d1_trend_prev_day_high        float32
 66   dist_d1_trend_prev_day_low         float32
 67   dist_d1_trend_prev_week_high       float32
 68   dist_d1_trend_prev_week_low        float32
 69   dist_d1_trend_prev_month_high      float32
 70   dist_d1_trend_prev_month_low       float32
 71   dist_d1_ha_ha_open                 float32
 72   dist_d1_ha_ha_high                 float32
 73   dist_d1_ha_ha_low                  float32
 74   dist_d1_ha_ha_close                float32
 75   dist_open_d1                       float32
 76   dist_high_d1                       float32
 77   dist_low_d1                        float32
 78   dist_close_d1                      float32
 79   dist_spy_m5_yest_high              float32
 80   dist_spy_m5_yest_low               float32
 81   dist_spy_m5_yest_close             float32
 82   dist_spy_m5_hod                    float32
 83   dist_spy_m5_lod                    float32
 84   dist_spy_m5_session_open           float32
 85   dist_spy_m5_ema_8                  float32
 86   dist_spy_m5_vwap                   float32
 87   dist_spy_d1_sma_20                 float32
 88   dist_spy_d1_sma_50                 float32
 89   dist_spy_d1_sma_200                float32
 90   dist_spy_d1_ema_8                  float32
 91   dist_spy_d1_ema_21                 float32
 92   dist_spy_d1_high_52w               float32
 93   dist_spy_d1_low_52w                float32
 94   dist_spy_d1_prev_day_high          float32
 95   dist_spy_d1_prev_day_low           float32
 96   d1_natr                            float32
 97   target_reg_5m_logret               float32
 98   target_cls_5m                      float32
 99   target_reg_30m_logret              float32
 100  target_cls_30m                     float32
 101  target_reg_1h_logret               float32
 102  target_cls_1h                      float32
 103  target_reg_2h_logret               float32
 104  target_cls_2h                      float32
 105  target_reg_4h_logret               float32
 106  target_cls_4h                      float32
 107  target_reg_1d_logret               float32
 108  target_cls_1d                      float32
 109  target_reg_3d_logret               float32
 110  target_cls_3d                      float32
 111  target_reg_5d_logret               float32
 112  target_cls_5d                      float32
 113  target_reg_10d_logret              float32
 114  target_cls_10d                     float32
dtypes: datetime64[us](1), float32(110), int8(2), object(2)
memory usage: 225.3+ MB

In [16]:
tmp.describe()

,timestamp,m5_rrs_rrs_spy,m5_rrs_rrs_sector,m5_mom_lrsi,m5_mom_tsi,m5_mom_squeeze_on,m5_vol_rel_vol,m5_vol_rel_cum_vol,m5_levels_chg_from_yest_close_pct,m5_levels_chg_from_open_pct,m5_ha_ha_color,spy_m5_avg_vol_50d,spy_m5_rel_vol,spy_m5_avg_cum_vol_50d,spy_m5_rel_cum_vol,spy_m5_yest_high,spy_m5_yest_low,spy_m5_yest_close,spy_m5_hod,spy_m5_lod,spy_m5_session_open,spy_m5_chg_from_yest_close_pct,spy_m5_chg_from_open_pct,spy_m5_lrsi,spy_m5_tsi,spy_m5_squeeze_on,spy_m5_ema_8,spy_m5_vwap,spy_d1_sma_20,spy_d1_sma_50,spy_d1_sma_200,spy_d1_ema_8,spy_d1_ema_21,spy_d1_atr_14,spy_d1_high_52w,spy_d1_low_52w,spy_d1_prev_day_high,spy_d1_prev_day_low,d1_trend_atr_14,d1_rrs_rrs_spy_5,d1_rrs_rrs_spy_5_sma,d1_rrs_rrs_sec_5,d1_rrs_rrs_sec_5_sma,d1_rrs_rrs_spy_12,d1_rrs_rrs_spy_12_sma,d1_rrs_rrs_sec_12,d1_rrs_rrs_sec_12_sma,d1_rrs_rrs_spy_25,d1_rrs_rrs_spy_25_sma,d1_rrs_rrs_sec_25,d1_rrs_rrs_sec_25_sma,d1_ha_ha_color,d1_lrsi_laguerre_rsi_0.7,d1_adx_adx,d1_adx_plus_di,d1_adx_minus_di,time_weekday,time_sin,time_cos,month_sin,month_cos,dist_m5_ma_ema_3,dist_m5_ma_ema_8,dist_m5_ma_vwap,dist_m5_levels_yest_high,dist_m5_levels_yest_low,dist_m5_levels_yest_close,dist_m5_levels_hod,dist_m5_levels_lod,dist_m5_levels_session_open,dist_m5_ha_ha_open,dist_m5_ha_ha_high,dist_m5_ha_ha_low,dist_m5_ha_ha_close,dist_d1_trend_sma_20,dist_d1_trend_sma_50,dist_d1_trend_sma_100,dist_d1_trend_sma_200,dist_d1_trend_ema_8,dist_d1_trend_ema_21,dist_d1_trend_high_52w,dist_d1_trend_low_52w,dist_d1_trend_prev_day_high,dist_d1_trend_prev_day_low,dist_d1_trend_prev_week_high,dist_d1_trend_prev_week_low,dist_d1_trend_prev_month_high,dist_d1_trend_prev_month_low,dist_d1_ha_ha_open,dist_d1_ha_ha_high,dist_d1_ha_ha_low,dist_d1_ha_ha_close,dist_open_d1,dist_high_d1,dist_low_d1,dist_close_d1,d1_natr,target_reg_5m_logret,target_cls_5m,target_reg_30m_logret,target_cls_30m,target_reg_1h_logret,target_cls_1h,target_reg_2h_logret,target_cls_2h,target_reg_4h_logret,target_cls_4h,target_reg_1d_logret,target_cls_1d,target_reg_3d_logret,target_cls_3d,target_reg_5d_logret,target_cls_5d,target_reg_10d_logret,target_cls_10d
count,506906,506447.000000,497370.000000,506906.000000,506906.000000,506906.000000,506906.000000,506906.000000,506906.000000,506906.000000,506906.00000,5.064470e+05,506447.000000,506447.0,506447.000000,506447.000000,506447.000000,506447.000000,506447.000000,506447.000000,506447.000000,506447.000000,506447.000000,506447.000000,506447.000000,506447.000000,506447.000000,506447.000000,505484.000000,503114.000000,491306.000000,506906.000000,506906.000000,505958.000000,487234.000000,487234.000000,506906.000000,506906.000000,505879.000000,506511.000000,506195.000000,506511.000000,506195.000000,505958.000000,505089.000000,505958.000000,505089.000000,504931.000000,503035.000000,504931.000000,503035.000000,506906.000000,506906.000000,504852.000000,505879.000000,505879.000000,506906.000000,506906.000000,506906.000000,5.069060e+05,5.069060e+05,506906.000000,506906.000000,506906.000000,506906.000000,506906.000000,506906.000000,5.069060e+05,5.069060e+05,506906.000000,506906.000000,5.069060e+05,5.069060e+05,506906.000000,505405.000000,503035.000000,499086.000000,491227.000000,506906.000000,506906.000000,487155.000000,487155.000000,506827.000000,506827.000000,506195.000000,506195.000000,503825.000000,503825.000000,506906.000000,506906.000000,506906.000000,506906.000000,506906.000000,506906.000000,506906.000000,506906.000000,505879.000000,506905.000000,506906.000000,506900.000000,506906.000000,506894.000000,506906.000000,506882.000000,506906.000000,506858.000000,506906.000000,506828.000000,506906.000000,506672.000000,506906.000000,506516.000000,506906.000000,506126.000000,506906.000000
mean,2012-10-17 23:12:00.520569,0.023114,0.023250,0.516153,1.803400,0.242299,1.016199,1.008444,0.001205,0.000454,0.01738,1.135138e+06,1.037175,44825812.0,1.023840,220.632584,217.982239,219.377045,220.330048,218.467300,219.428162,0.000230,0.000038,0.531633,2.159449,0.232627,219.440002,219.415024,218.900177,218.168274,214.695786,219.140778,218.661331,2.946660,237.693954,181.336243,220.584320,217.933975,1.092478,0.119032,0.119987,0.101223,0.101414,0.287943,0.288769,0.244055,0.244813,0.601223,0.601207,0.510620,0.518344,0.125562,0.602746,26.833893,25.509027,22.121223,2.022186,-0.171090,-0.864037,9.996308e-03,-1.252547e-02,-0.000006,-0.000023,-0.000014,0.012789,-0.014640,-0.000738,1.028824e-02,-1.079866e-02,-0.000225,-0.000017,1.684431e-03,-1.717987e-03,-0.000004,-0.005427,-0.011817,-0.021690,-0.047626,-0.002478,-0.005423,0.247300,-0.339629,0.012254,-0.015172,0.027568,-0.041089,0.052339,-0.108899,-0.001885,0.015993,-0.018652,-0.000836,-0.000757,0.012789,-0.014640,-0.000738,0.030061,0.000011,1.002326,0.000064,1.009081,0.000128,1.012975,0.000256,1.019453,0.000512,1.029907,0.000833,1.038832,0.002512,1.073740,0.004207,1.089466,0.008446,1.124946
min,2000-01-04 09:30:00,-21.756632,-18.964575,0.000000,-86.271149,0.000000,0.000022,0.008352,-0.522191,-0.141869,-1.00000,0.000000e+00,0.000010,0.0,0.000157,70.000000,67.099998,68.010002,68.190002,67.099998,67.949997,-0.111370,-0.084186,0.000000,-81.704666,0.000000,67.330193,68.099998,74.095001,79.107201,87.230301,70.911293,74.918747,0.740000,102.179001,67.099998,70.000000,67.099998,0.006421,-6.595678,-4.976721,-5.137199,-4.171329,-9.153005,-6.193616,-7.038302,-4.736570,-13.305948,-8.965094,-9.558327,-6.209555,-1.000000,0.000000,7.832256,4.720641,3.863365,0.000000,-0.866025,-1.000000,-1.000000e+00,-1.000000e+00,-0.058186,-0.092676,-0.088739,-0.130507,-0.226928,-0.145173,-5.730647e-08,-1.978967e-01,-0.139958,-0.116468,-5.883118e-08,-1.697856e-01,-0.066392,-0.227032,-0.314065,-0.423101,-0.513000,-0.188025,-0.206872,-0.101978,-0.758495,-0.182360,-0.265728,-0.256340,-0.291781,-0.493142,-0.572051,-0.203460,-0.130507,-0.226928,-0.161461,-0.221096,-0.130507,-0.226928,-0.145173,0.008479,-0.636152,0.000000,-0.654064,0.000000,-0.719189,0.000000,-0.715615,0.000000,-0.716872,0.000000,-0.731339,0.000000,-0.872263,0.000000,-0.880211,0.000000,-0.992141,0.000000
25%,2006-06-01 15:41:15,-1.154561,-1.045719,0.110233,-12.567369,0.000000,0.574928,0.698423,-0.007704,-0.006698,-1.00000,4.630160e+05,0.541397,15132454.0,0.743208,121.489998,120.080002,120.839996,121.300003,120.305000,120.820000,-0.003649,-0.002746,0.133978,-12.496847,0.000000,120.818497,120.802040,120.482498,120.787903,120.041176,120.584473,120.533577,1.456429,132.800003,106.589996,121.489998,120.099998,0.076579,-0.817343,-0.653417,-0.677355,-0.550283,-1.197067,-0.876046,-0.991445,-0.741039,-1.455565,-1.048837,-1.290180,-0.944396,-1.000000,0.233685,18.492939,18.865564,16.087460,1.000000,-0.591310,-0.976296,-5.000000e-01,-8.660254e-01,-0.000497,-0.001094,-0.003345,-0.000970,-0.024924,-0.010271,3.043098e-03,-1.416065e-02,-0.007608,-0.001142,4.018205e-04,-2.106360e-03,-0.000454,-0.045220,-0.077719,-0.118592,-0.178832,-0.023284,-0.041039,0.034302,-0.437628,-0.007231,-0.030988,-0.022580,-0.082187,-0.075295,-0.198184,-0.021409,0.000159,-0.030202,-0.011707,-0.015026,-0.000970,-0.024924,-0.010271,0.018670,-0.000852,1.000000,-0.002105,1.000000,-0.003029,1.000000,-0.004489,1.000000,-0.007016,1.000000,-0.009656,1.000000,-0.017078,1.000000,-0.022113,1.000000,-0.030029,1.000000
50%,2012-10-16 12:47:30,-0.008291,-0.008507,0.532128,1.412041,0.000000,0.817565,0.874278,0.001161,0.000374,1.00000,7.789452e+05,0.811515,31387416.0,0.926182,152.107193,150.410004,151.250000,151.800003,150.699997,151.250000,0.000442,0.000181,0.559551,2.266133,0.000000,151.286591,151.222061,151.020004,150.136200,148.456543,150.985931,150.192490,2.023571,159.710007,134.300003,152.020004,150.380005,0.348471,0.053302,0.082388,0.067164,0.069313,0.270478,0.270563,0.192676,0.221744,0.640560,0.766056,0.492722,0.517465,1.000000,0.704096,25.087152,24.722630,21.307682,2.000000,-0.195090,-0.906308,1.224647e-16,-1.836970e-16,-0.000014,-0.000046,-0.000099,0.008846,-0.012425,-0.001160,6.785900e-03,-7.611309e-03,-0.000374,-0.000036,9.683029e-04,-1.024395e-03,-0.000006,-0.013618,-0.029249,-0.054349,-0.105985,-0.006011,-0.013765,0.097026,-0.342059,0.007986,-0.014174,0.014509,-0.042512,0.004500,-0.123619,-0.004376,0.010533,-0.015968,-0.001660,-0.001776,0.008846,-0.012425,-0.001160,0.025591,0.000000,1.000000,0.000019,1.000000,0.000092,1.000000,0.000258,1.000000,0.000624,1.000000,0.001151,1.000000,0.003581,1.000000,0.006463,1.000000,0.012957,1.000000
75%,2019-03-08 11:33:45,1.145878,1.041861,0.937693,15.756638,0.000000,1.190132,1.137173,0.010377,0.007666,1.00000,1.386118e+06,1.239721,57809300.0,1.182112,284.109985,280.666199,282.549988,283.803406,281.329987,282.529999,0.004567,0.003028,0.960838,16.830482,0.000000,282.428436,282.404480,282.483002,282.003601,277.236908,281.883423,281.358276,3.584643,294.950012,232.610001,284.054993,280.630005,1.092321,0.976991,0.862975,0.843632,0.715291,1.712066,1.518712,1.413740,1.204581,2.808871,2.438091,2.193527,1.910856,1.000000,1.000000,32.888927,31.404911,27.462088,3.000000,0.237686,-0.793353,8.660254e-01,5.000000e-01,0.000480,0.001024,0.003113,0.022797,-0.002350,0.007764,1.351093e-02,-3.706289e-03,0.006743,0.001095,2.062471e-03,-4.472099e-04,0.000441,0.022620,0.025341,0.023230,0.017552,0.014118,0.019520,0.253108,-0.233859,0.027022,0.001383,0.060397,-0.004181,0.102374,-0.043306,0.014886,0.026291,-0.004393,0.008985,0.012382,0.022797,-0.002350,0.007764,0.035325,0.000869,1.000000,0.002228,1.000000,0.003277,1.000000,0.005081,1.000000,0.008332,1.000000,0.011790,1.000000,0.023526,2.000000,0.032356,2.000000,0.051674,2.000000
max,2025-07-25 16:00:00,29.894161,19.256159,1.000000,86.437210,1.000000,65.585503,48.316849,0.169827,0.162734,1.00000,1.679379e+07,58.866280,445251904.0,58.866280,636.150024,633.989990,634.340027,637.579895,634.929993,635.059998,0.111062,0.104734,1.000000,87.375809,1.000000,637.385864,636.513977,624.877991,607.186218,587.019592,630.977722,623.228088,24.058571,637.579895,493.859985,636.150024,633.989990,13.846472,8.596402,7.150587,6.948868,5.798776,10.056437,8.017786,9.210276,6.783309,12.583515,9.249664,11.025200,8.275477,1.000000,1.000000,70.784233,61.373177,57.836189,4.000000,0.608761,-0.500000,1.000000e+00,1.000000e+00,0.444814,0.689108,0.149668,1.110013,0.887132,1.092885,2.306855e-01,5.737094e-08,0.165323,0.888913,8.889126e-01,5.848003e-08,0.057399,1.423612,1.546963,1.692119,2.343837,1.106418,1.258856,4.185786,0.115171,1.283508,1.042300,1.847004,1.272588,2.960913,1.669324,1.186899,1.186899,0.887132,1.005929,0.933685,1.110013,0.887132,1.092885,0.263089,0.123566,2.000000,0.135902,2.000000,0.141438,2.000000,0.163295,2.000000,0.187798,2.000000,0.206563,2.000000,0.253839,2.000000,0.304713,2.000000,0.318117,2.000000
std,NaN,2.150877,1.978894,0.387427,21.518599,0.428475,0.893539,0.654815,0.020566,0.015140,0.99985,1.141395e+06,0.908548,45315812.0,0.466698,134.786804,133.426453,134.171539,134.691391,133.728043,134.228409,0.009353,0.006715,0.387030,21.652735,0.422507,134.252213,134.224380,133.394135,132.184692,126.880821,133.861206,133.194870,2.412066,140.174408,106.691475,134.762939,133.403046,1.659423,1.530655,1.262540,1.296560,1.059982,2.353643,1.913062,1.939660,1.560186,3.342995,2.726703,2.770633,2.276949,0.992087,0.385097,10.722382,8.742121,8.124407,1.398888,0.453304,0.136692,7.083310e-01,7.056999e-01,0.001727,0.003635,0.007137,0.027787,0.025676,0.023547,1.126989e-02,1.088919e-02,0.015128,0.003724,2.887566e-03,2.395342e-03,0.001198,0.078448,0.129294,0.192862,0.264857,0.042076,0.070088,0.450041,0.157191,0.038619,0.035855,0.099422,0.075183,0.253310,0.163124,0.040298,0.034245,0.027573,0.024780,0.029603,0.027787,0.025676,0.023547,0.018220,0.002931,0.547486,0.006810,0.552263,0.009559,0.562654,0.013425,0.585923,0.018951,0.621986,0.024168,0.650286,0.041494,0.675441,0.053801,0.686279,0.077970,0.703512

In [15]:
tmp.columns.tolist()

['timestamp',
 'm5_rrs_rrs_spy',
 'm5_rrs_rrs_sector',
 'm5_mom_lrsi',
 'm5_mom_tsi',
 'm5_mom_squeeze_on',
 'm5_vol_rel_vol',
 'm5_vol_rel_cum_vol',
 'm5_levels_chg_from_yest_close_pct',
 'm5_levels_chg_from_open_pct',
 'm5_ha_ha_color',
 'ticker',
 'spy_m5_avg_vol_50d',
 'spy_m5_rel_vol',
 'spy_m5_avg_cum_vol_50d',
 'spy_m5_rel_cum_vol',
 'spy_m5_yest_high',
 'spy_m5_yest_low',
 'spy_m5_yest_close',
 'spy_m5_hod',
 'spy_m5_lod',
 'spy_m5_session_open',
 'spy_m5_chg_from_yest_close_pct',
 'spy_m5_chg_from_open_pct',
 'spy_m5_lrsi',
 'spy_m5_tsi',
 'spy_m5_squeeze_on',
 'spy_m5_ema_8',
 'spy_m5_vwap',
 'spy_d1_sma_20',
 'spy_d1_sma_50',
 'spy_d1_sma_200',
 'spy_d1_ema_8',
 'spy_d1_ema_21',
 'spy_d1_atr_14',
 'spy_d1_high_52w',
 'spy_d1_low_52w',
 'spy_d1_prev_day_high',
 'spy_d1_prev_day_low',
 'd1_trend_atr_14',
 'd1_rrs_rrs_spy_5',
 'd1_rrs_rrs_spy_5_sma',
 'd1_rrs_rrs_sec_5',
 'd1_rrs_rrs_sec_5_sma',
 'd1_rrs_rrs_spy_12',
 'd1_rrs_rrs_spy_12_sma',
 'd1_rrs_rrs_sec_12',
 'd1_rrs_rrs_sec_12_sma',
 'd1_rrs_rrs_spy_25',
 'd1_rrs_rrs_spy_25_sma',
 'd1_rrs_rrs_sec_25',
 'd1_rrs_rrs_sec_25_sma',
 'd1_ha_ha_color',
 'd1_lrsi_laguerre_rsi_0.7',
 'd1_adx_adx',
 'd1_adx_plus_di',
 'd1_adx_minus_di',
 'ticker_d1',
 'time_weekday',
 'time_sin',
 'time_cos',
 'month_sin',
 'month_cos',
 'dist_m5_ma_ema_3',
 'dist_m5_ma_ema_8',
 'dist_m5_ma_vwap',
 'dist_m5_levels_yest_high',
 'dist_m5_levels_yest_low',
 'dist_m5_levels_yest_close',
 'dist_m5_levels_hod',
 'dist_m5_levels_lod',
 'dist_m5_levels_session_open',
 'dist_m5_ha_ha_open',
 'dist_m5_ha_ha_high',
 'dist_m5_ha_ha_low',
 'dist_m5_ha_ha_close',
 'dist_d1_trend_sma_20',
 'dist_d1_trend_sma_50',
 'dist_d1_trend_sma_100',
 'dist_d1_trend_sma_200',
 'dist_d1_trend_ema_8',
 'dist_d1_trend_ema_21',
 'dist_d1_trend_high_52w',
 'dist_d1_trend_low_52w',
 'dist_d1_trend_prev_day_high',
 'dist_d1_trend_prev_day_low',
 'dist_d1_trend_prev_week_high',
 'dist_d1_trend_prev_week_low',
 'dist_d1_trend_prev_month_high',
 'dist_d1_trend_prev_month_low',
 'dist_d1_ha_ha_open',
 'dist_d1_ha_ha_high',
 'dist_d1_ha_ha_low',
 'dist_d1_ha_ha_close',
 'dist_open_d1',
 'dist_high_d1',
 'dist_low_d1',
 'dist_close_d1',
 'd1_natr',
 'target_reg_5m_logret',
 'target_cls_5m',
 'target_reg_30m_logret',
 'target_cls_30m',
 'target_reg_1h_logret',
 'target_cls_1h',
 'target_reg_2h_logret',
 'target_cls_2h',
 'target_reg_4h_logret',
 'target_cls_4h',
 'target_reg_1d_logret',
 'target_cls_1d',
 'target_reg_3d_logret',
 'target_cls_3d',
 'target_reg_5d_logret',
 'target_cls_5d',
 'target_reg_10d_logret',
 'target_cls_10d']

In [5]:
tmp.columns.tolist()

['timestamp',
 'm5_rrs_rrs_spy',
 'm5_rrs_rrs_sector',
 'm5_mom_lrsi',
 'm5_mom_tsi',
 'm5_mom_squeeze_on',
 'm5_vol_rel_vol',
 'm5_vol_rel_cum_vol',
 'm5_levels_chg_from_yest_close_pct',
 'm5_levels_chg_from_open_pct',
 'm5_ha_ha_color',
 'ticker',
 'spy_m5_rel_vol',
 'spy_m5_rel_cum_vol',
 'spy_m5_chg_from_yest_close_pct',
 'spy_m5_chg_from_open_pct',
 'spy_m5_lrsi',
 'spy_m5_tsi',
 'spy_m5_squeeze_on',
 'spy_d1_atr_14',
 'd1_trend_atr_14',
 'd1_rrs_rrs_spy_5',
 'd1_rrs_rrs_spy_5_sma',
 'd1_rrs_rrs_sec_5',
 'd1_rrs_rrs_sec_5_sma',
 'd1_rrs_rrs_spy_12',
 'd1_rrs_rrs_spy_12_sma',
 'd1_rrs_rrs_sec_12',
 'd1_rrs_rrs_sec_12_sma',
 'd1_rrs_rrs_spy_25',
 'd1_rrs_rrs_spy_25_sma',
 'd1_rrs_rrs_sec_25',
 'd1_rrs_rrs_sec_25_sma',
 'd1_ha_ha_color',
 'd1_lrsi_laguerre_rsi_0.7',
 'd1_adx_adx',
 'd1_adx_plus_di',
 'd1_adx_minus_di',
 'ticker_d1',
 'time_weekday',
 'time_sin',
 'time_cos',
 'month_sin',
 'month_cos',
 'dist_m5_ma_ema_3',
 'dist_m5_ma_ema_8',
 'dist_m5_ma_vwap',
 'dist_m5_levels_yest_high',
 'dist_m5_levels_yest_low',
 'dist_m5_levels_yest_close',
 'dist_m5_levels_hod',
 'dist_m5_levels_lod',
 'dist_m5_levels_session_open',
 'dist_m5_ha_ha_open',
 'dist_m5_ha_ha_high',
 'dist_m5_ha_ha_low',
 'dist_m5_ha_ha_close',
 'dist_d1_trend_sma_20',
 'dist_d1_trend_sma_50',
 'dist_d1_trend_sma_100',
 'dist_d1_trend_sma_200',
 'dist_d1_trend_ema_8',
 'dist_d1_trend_ema_21',
 'dist_d1_trend_high_52w',
 'dist_d1_trend_low_52w',
 'dist_d1_trend_prev_day_high',
 'dist_d1_trend_prev_day_low',
 'dist_d1_trend_prev_week_high',
 'dist_d1_trend_prev_week_low',
 'dist_d1_trend_prev_month_high',
 'dist_d1_trend_prev_month_low',
 'dist_d1_ha_ha_open',
 'dist_d1_ha_ha_high',
 'dist_d1_ha_ha_low',
 'dist_d1_ha_ha_close',
 'dist_open_d1',
 'dist_high_d1',
 'dist_low_d1',
 'dist_close_d1',
 'dist_spy_m5_yest_high',
 'dist_spy_m5_yest_low',
 'dist_spy_m5_yest_close',
 'dist_spy_m5_hod',
 'dist_spy_m5_lod',
 'dist_spy_m5_session_open',
 'dist_spy_m5_ema_8',
 'dist_spy_m5_vwap',
 'dist_spy_d1_sma_20',
 'dist_spy_d1_sma_50',
 'dist_spy_d1_sma_200',
 'dist_spy_d1_ema_8',
 'dist_spy_d1_ema_21',
 'dist_spy_d1_high_52w',
 'dist_spy_d1_low_52w',
 'dist_spy_d1_prev_day_high',
 'dist_spy_d1_prev_day_low',
 'd1_natr',
 'target_reg_5m_logret',
 'target_cls_5m',
 'target_reg_30m_logret',
 'target_cls_30m',
 'target_reg_1h_logret',
 'target_cls_1h',
 'target_reg_2h_logret',
 'target_cls_2h',
 'target_reg_4h_logret',
 'target_cls_4h',
 'target_reg_1d_logret',
 'target_cls_1d',
 'target_reg_3d_logret',
 'target_cls_3d',
 'target_reg_5d_logret',
 'target_cls_5d',
 'target_reg_10d_logret',
 'target_cls_10d']

In [ ]:
missingCols = pd.read_parquet("/opt/rws/repos/RWS_LightGBM/data/reprocessed/final_merged_with_spy/ml_ready_with_targets/CRWV.parquet")
pd.options.display.max_columns = None
display(missingCols)

,timestamp,m5_rrs_rrs_spy,m5_rrs_rrs_sector,m5_mom_lrsi,m5_mom_tsi,m5_mom_squeeze_on,m5_vol_rel_vol,m5_vol_rel_cum_vol,m5_levels_chg_from_yest_close_pct,m5_levels_chg_from_open_pct,m5_ha_ha_color,ticker,spy_m5_avg_vol_50d,spy_m5_rel_vol,spy_m5_avg_cum_vol_50d,spy_m5_rel_cum_vol,spy_m5_yest_high,spy_m5_yest_low,spy_m5_yest_close,spy_m5_hod,spy_m5_lod,spy_m5_session_open,spy_m5_chg_from_yest_close_pct,spy_m5_chg_from_open_pct,spy_m5_lrsi,spy_m5_tsi,spy_m5_squeeze_on,spy_m5_ema_8,spy_m5_vwap,spy_d1_sma_20,spy_d1_sma_50,spy_d1_sma_200,spy_d1_ema_8,spy_d1_ema_21,spy_d1_atr_14,spy_d1_high_52w,spy_d1_low_52w,spy_d1_prev_day_high,spy_d1_prev_day_low,d1_rrs_rrs_spy_5,d1_rrs_rrs_spy_5_sma,d1_rrs_rrs_sec_5,d1_rrs_rrs_sec_5_sma,d1_rrs_rrs_spy_12,d1_rrs_rrs_spy_12_sma,d1_rrs_rrs_sec_12,d1_rrs_rrs_sec_12_sma,d1_rrs_rrs_spy_25,d1_rrs_rrs_spy_25_sma,d1_rrs_rrs_sec_25,d1_rrs_rrs_sec_25_sma,d1_ha_ha_color,d1_lrsi_laguerre_rsi_0.7,d1_adx_adx,d1_adx_plus_di,d1_adx_minus_di,ticker_d1,time_weekday,time_sin,time_cos,month_sin,month_cos,dist_m5_ma_ema_3,dist_m5_ma_ema_8,dist_m5_ma_vwap,dist_m5_levels_yest_high,dist_m5_levels_yest_low,dist_m5_levels_yest_close,dist_m5_levels_hod,dist_m5_levels_lod,dist_m5_levels_session_open,dist_m5_ha_ha_open,dist_m5_ha_ha_high,dist_m5_ha_ha_low,dist_m5_ha_ha_close,dist_d1_ha_ha_open,dist_d1_ha_ha_high,dist_d1_ha_ha_low,dist_d1_ha_ha_close,dist_open_d1,dist_high_d1,dist_low_d1,dist_close_d1,target_reg_5m_logret,target_cls_5m,target_reg_30m_logret,target_cls_30m,target_reg_1h_logret,target_cls_1h,target_reg_2h_logret,target_cls_2h,target_reg_4h_logret,target_cls_4h,target_reg_1d_logret,target_cls_1d,target_reg_3d_logret,target_cls_3d,target_reg_5d_logret,target_cls_5d,target_reg_10d_logret,target_cls_10d
0,2025-03-31 09:30:00,2.374318,3.515350,0.060217,18.460253,0.0,1.000000,1.000000,-0.044166,-0.010392,-1,CRWV,6.199086e+05,1.222851,6.199086e+05,1.222851,566.267517,555.070007,555.500000,550.630005,549.780029,549.820007,-0.009681,0.000549,0.284461,-28.588776,0.0,554.495850,550.177307,566.235474,587.746277,574.471436,563.989380,570.122803,9.001785,613.229980,493.859985,566.267517,555.070007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,CRWV,0,0.608761,-0.793353,8.660254e-01,0.5,0.023014,0.038461,0.002713,0.101076,-0.016540,0.046206,0.010501,-2.362825e-03,0.010501,0.045972,0.045972,-2.362825e-03,0.004660,0.035049,0.101076,-0.016540,0.038658,0.023891,0.101076,-0.016540,0.046206,-0.014603,0,-0.028358,0,-0.044834,0,-0.037448,0,-0.048961,0,-0.030386,0,0.488794,2,0.211365,2,0.135105,2
1,2025-03-31 09:35:00,2.563766,4.020332,0.059597,10.083438,0.0,1.000000,1.000000,-0.058023,-0.024739,-1,CRWV,8.231355e+05,1.664703,1.443044e+06,1.474890,566.267517,555.070007,555.500000,550.630005,548.330017,549.820007,-0.011755,-0.001546,0.239304,-39.593124,0.0,553.267883,549.528809,566.235474,587.746277,574.471436,563.989380,570.122803,9.001785,613.229980,493.859985,566.267517,555.070007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,CRWV,0,0.591310,-0.806445,8.660254e-01,0.5,0.019031,0.041796,0.008941,0.117274,-0.002073,0.061597,0.025366,-9.531717e-03,0.025366,0.040399,0.040399,-9.531717e-03,0.004972,0.050275,0.117274,-0.002073,0.053938,0.038953,0.117274,-0.002073,0.061597,-0.003544,0,-0.017815,0,-0.037671,0,-0.023662,0,-0.033258,0,0.021406,2,0.512135,2,0.233590,2,0.151542,2
2,2025-03-31 09:40:00,3.281104,4.425195,0.034157,3.140623,0.0,1.000000,1.000000,-0.061355,-0.028189,-1,CRWV,6.098399e+05,1.683835,2.052884e+06,1.536961,566.267517,555.070007,555.500000,550.630005,548.210022,549.820007,-0.012835,-0.002637,0.201241,-46.994057,0.0,552.179504,549.274231,566.235474,587.746277,574.471436,563.989380,570.122803,9.001785,613.229980,493.859985,566.267517,555.070007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,CRWV,0,0.573576,-0.819152,8.660254e-01,0.5,0.011325,0.035385,0.008352,0.121240,0.001470,0.065366,0.029007,-7.886630e-03,0.029007,0.026316,0.026316,-7.886630e-03,0.000769,0.054003,0.121240,0.001470,0.057679,0.042641,0.121240,0.001470,0.065366,-0.021756,0,-0.013322,0,-0.030813,0,-0.014813,0,-0.032331,0,0.011827,2,0.493649,2,0.236818,2,0.158713,2
3,2025-03-31 09:45:00,2.461625,3.206654,0.050550,-4.681344,0.0,1.000000,1.000000,-0.081556,-0.049104,-1,CRWV,5.387004e+05,1.684742,2.591584e+06,1.567679,566.267517,555.070007,555.500000,550.630005,546.940002,549.820007,-0.015239,-0.005065,0.200799,-53.254848,0.0,551.036255,548.870850,566.235474,587.746277,574.471436,563.989380,570.122803,9.001785,613.229980,493.859985,566.267517,555.070007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,CRWV,0,0.555570,-0.831470,8.660254e-01,0.5,0.016784,0.045234,0.024882,0.145902,0.023497,0.088798,0.051639,-4.169068e-08,0.051639,0.035835,0.035835,-4.169068e-08,0.011646,0.077186,0.145902,0.023497,0.080943,0.065574,0.145902,0.023497,0.088798,-0.007404,0,0.000000,1,-0.009333,0,0.006264,2,-0.010644,0,0.027753,2,0.401814,2,0.258996,2,0.172253,2
4,2025-03-31 09:50:00,1.413085,2.076755,0.069717,-11.460896,0.0,1.000000,1.000000,-0.088331,-0.056118,-1,CRWV,4.683046e+05,2.456177,3.059889e+06,1.703660,566.267517,555.070007,555.500000,550.630005,546.869995,549.820007,-0.013564,-0.003374,0.218601,-54.333153,0.0,550.353760,548.599609,566.235474,587.746277,574.471436,563.989380,570.122803,9.001785,613.229980,493.859985,566.267517,555.070007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,CRWV,0,0.537300,-0.843391,8.660254e-01,0.5,0.012170,0.041224,0.026510,0.154418,0.031104,0.096890,0.059455,-2.202037e-03,0.059455,0.031349,0.031349,-2.202037e-03,0.004817,0.085191,0.154418,0.031104,0.088976,0.073493,0.154418,0.031104,0.096890,0.011358,2,0.005764,2,0.001100,2,0.015297,2,-0.003999,0,0.039665,2,0.415870,2,0.265978,2,0.178737,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6314,2025-07-25 15:40:00,-3.118351,-2.368732,0.000000,-13.696130,0.0,0.459220,0.390223,-0.041597,-0.039440,-1,CRWV,7.591495e+05,0.908817,3.921322e+07,0.726364,636.150024,633.989990,634.340027,637.579895,634.840027,635.059998,0.004911,0.003771,1.000000,21.460234,1.0,637.385864,636.374207,624.877991,607.186218,587.019592,630.977722,623.228088,4.153779,637.579895,481.799988,636.150024,633.989990,-2.509716,-2.19399,-1.204197,-1.737524,-6.021096,-4.979145,-4.802544,-4.877327,-9.747992,-1.527503,-9.089523,-2.691249,-1.0,0.0,27.165636,18.337065,28.110655,CRWV,4,-0.819152,-0.573576,1.224647e-16,-1.0,0.001101,0.002147,0.006838,0.096528,0.041667,0.043403,0.041059,-8.420110e-03,0.041059,0.002260,0.003125,-4.340145e-04,0.001215,0.118933,0.118933,0.041667,0.068294,0.091580,0.096528,0.041667,0.043403,0.000260,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1
6315,2025-07-25 15:45:00,-1.170573,0.091194,0.000000,-14.770488,0.0,0.429734,0.390657,-0.041348,-0.039190,-1,CRWV,8.236433e+05,0.846949,4.003687e+07,0.728845,636.150024,633.989990,634.340027,637.579895,634.840027,635.059998,0.004682,0.003543,0.902754,19.143709,1.0,637.369019,636.397034,624.877991,607.186218,587.019592,630.977722,623.228088,4.153779,637.579895,481.799988,636.150024,633.989990,-2.509716,-2.19399,-1.204197,-1.737524,-6.021096,-4.979145,-4.802544,-4.877327,-9.747992,-1.527503,-9.089523,-2.691249,-1.0,0.0,27.165636,18.337065,28.110655,CRWV,4,-0.831470,-0.555570,1.224647e-16,-1.0,0.000420,0.001467,0.006497,0.096242,0.041395,0.043131,0.040788,-8.678267e-03,0.040788,0.001477,0.001909,-1.648868e-03,-0.000105,0.118642,0.118642,0.041395,0.068016,0.091296,0.096242,0.041395,0.043131,-0.000087,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1
6316,2025-07-25 15:50:00,-1.164446,-0.524057,0.000000,-15.717241,0.0,0.475529,0.391720,-0.041431,-0.039273,-1,CRWV,1.241331e+06,0.684967,4.127820e+07,0.727525,636.150024,633.989990,634.340027,637.579895,634.840027,635.059998,0.004493,0.003354,0.586184,15.525219,1.0,637.329224,636.420776,624.877991,607.186218,587.019592,630.977722,623.228088,4.153779,637.579895,481.799988,636.150024,633.989990,-2.509716,-2.19399,-1.204197,-1.737524,-6.021096,-4.979145,-4.802544,-4.877327,-9.747992,-1.527503,-9.089523,-2.691249,-1.0,0.0,27.165636,18.337065,28.110655,CRWV,4,-0.843391,-0.537300,1.224647e-16,-1.0,0.000253,0.001209,0.006481,0.096337,0.041486,0.043222,0.040878,-8.592229e-03,0.040878,0.000773,0.001128,-1.909391e-03,-0.000144,0.118739,0.118739,0.041486,0.068109,0.091390,0.096337,0.041486,0.043222,0.004935,2,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1
6317,2025-07-25 15:55:00,2.240808,3.221995,0.126817,-12.443689,0.0,0.414738,0.392083,-0.036689,-0.034520,1,CRWV,1.883291e+06,1.162845,4.316149e+07,0.746520,636.150024,633.989990,634.340027,637.579895,634.840027,635.059998,0.003862,0.002724,0.379329,7.227488,0.0,637.209412,636.451416,624.877991,607.186218,587.019592,630.977722,623.228088,4.153779,637.579895,481.799988,636.150024,633.989990,-2.509716,-2.19399,-1.204197,-1.737524,-6.021096,-4.979145,-4.802544,-4.877327,-9.747992,-1.527503,-9.089523,-2.691249,-1.0,0.0,27.165636,18.337065,28.110655,CRWV,4,-0.854912,-0.518773,1.224647e-16,-1.0,-0.002335,-0.002893,0.001476,0.090940,0.036359,0.038086,0.035754,-1.347264e-02,0.035754,-0.004610,0.001036,-5.527235e-03,-0.002334,0.113231,0.113231,0.036359,0.062851,0.086018,0.090940,0.036359,0.038086,-0.002075,0,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1
6318,2025-07-25 16:00:00,1.929083,4.267305,0.147922,-11.150314,0.0,0.440050,0.393508,-0.038686,-0.036521,1,CRWV,4.573759e+06,1.108427,4.773525e+07,0.781196,636.150024,633.989990,634.340027,637.579895,634.840027,635.059998,0.004036,0.002897,0.381032,2.336901,0.0,637.140625,636.513977,624.877991,607.186218,587.019592,630.977722,623.228088,4.153779,637.579895,481.799988,636.150024,633.989990,-2.509716,-2.19399,-1.204197,-1.737524,-6.021096,-4.979145,-4.802544,-4.877327,-9.747992,-1.527503,-9.089523,-2.691249,-1.0,0.0,27.165636,18.337065,28.110655,CRWV,4,-0.866025,-0.500000,1.224647e-16,-1.0,-0.000132,-0.000640,0.003464,0.093206,0.038511,0.040242,0.037906,-1.142360e-02,0.037906,-0.001402,0.002769,-1.401920e-03,0.000974,0.115544,0.115544,0.038511,0.065058,0.088273,0.093206,0.038511,0.040242,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1

In [4]:
len(tmp)

506906

In [5]:
tmp2 = tmp.dropna()
len(tmp2)

479216

In [19]:
import os

# Define the path to your folder
folder_path = '/opt/rws/repos/RWS_LightGBM/data/reprocessed/final_merged_with_spy/ml_ready_with_targets'

# Get all files, filter for .parquet, and strip the extension
tickers = [f.replace('.parquet', '') for f in os.listdir(folder_path) if f.endswith('.parquet')]

len(tickers)

318

In [7]:
import random as rd
print(rd.sample(tickers, 10))

['STT', 'CEG', 'WMT', 'IBM', 'DD', 'XPEV', 'U', 'LULU', 'NUE', 'NFLX']

In [8]:
import os
import pandas as pd
import random
from pathlib import Path
import datetime

# 1. Setup paths
# Replace with the actual path to your parquet files

# 2. Identify all ticker names in the folder
# This scans for *.parquet and removes the extension
tickers = [f.replace('.parquet', '') for f in os.listdir(folder_path) if f.endswith('.parquet')]

# 3. Your sampling logic
# Ensure we don't try to sample more tickers than we actually have
sample_size = min(len(tickers), 5)
sample_tickers = random.sample(tickers, sample_size)
random_samples = []


for ticker in sample_tickers:
    ticker_path = os.path.join(folder_path, f"{ticker}.parquet")
    df = pd.read_parquet(ticker_path)
    
    if not df.empty:
        # 1. Ensure the index or timestamp column is in datetime format
        if not isinstance(df.index, pd.DatetimeIndex):
            # If the timestamp is a column, set it as index first
            if 'timestamp' in df.columns:
                df.index = pd.to_datetime(df['timestamp'])
            else:
                df.index = pd.to_datetime(df.index)

        # 2. Filter for exactly 9:30 AM
        # This assumes the data is already in New York time
        df_at_open = df[df.index.time == datetime.time(9, 30)]
        
        # 3. Sample from the filtered subset
        if not df_at_open.empty:
            random_samples.append(df_at_open.sample(n=1))

# 4. Combine and display results
if random_samples:
    df_samples = pd.concat(random_samples)
    display(df_samples)
else:
    print("No market open data found to sample.")

,timestamp,m5_rrs_rrs_spy,m5_rrs_rrs_sector,m5_mom_lrsi,m5_mom_tsi,m5_mom_squeeze_on,m5_vol_rel_vol,m5_vol_rel_cum_vol,m5_levels_chg_from_yest_close_pct,m5_levels_chg_from_open_pct,m5_ha_ha_color,ticker,spy_m5_avg_vol_50d,spy_m5_rel_vol,spy_m5_avg_cum_vol_50d,spy_m5_rel_cum_vol,spy_m5_yest_high,spy_m5_yest_low,spy_m5_yest_close,spy_m5_hod,spy_m5_lod,spy_m5_session_open,spy_m5_chg_from_yest_close_pct,spy_m5_chg_from_open_pct,spy_m5_lrsi,spy_m5_tsi,spy_m5_squeeze_on,spy_m5_ema_8,spy_m5_vwap,spy_d1_sma_20,spy_d1_sma_50,spy_d1_sma_200,spy_d1_ema_8,spy_d1_ema_21,spy_d1_atr_14,spy_d1_high_52w,spy_d1_low_52w,spy_d1_prev_day_high,spy_d1_prev_day_low,d1_trend_atr_14,d1_rrs_rrs_spy_5,d1_rrs_rrs_spy_5_sma,d1_rrs_rrs_sec_5,d1_rrs_rrs_sec_5_sma,d1_rrs_rrs_spy_12,d1_rrs_rrs_spy_12_sma,d1_rrs_rrs_sec_12,d1_rrs_rrs_sec_12_sma,d1_rrs_rrs_spy_25,d1_rrs_rrs_spy_25_sma,d1_rrs_rrs_sec_25,d1_rrs_rrs_sec_25_sma,d1_ha_ha_color,d1_lrsi_laguerre_rsi_0.7,d1_adx_adx,d1_adx_plus_di,d1_adx_minus_di,ticker_d1,time_weekday,time_sin,time_cos,month_sin,month_cos,dist_m5_ma_ema_3,dist_m5_ma_ema_8,dist_m5_ma_vwap,dist_m5_levels_yest_high,dist_m5_levels_yest_low,dist_m5_levels_yest_close,dist_m5_levels_hod,dist_m5_levels_lod,dist_m5_levels_session_open,dist_m5_ha_ha_open,dist_m5_ha_ha_high,dist_m5_ha_ha_low,dist_m5_ha_ha_close,dist_d1_trend_sma_20,dist_d1_trend_sma_50,dist_d1_trend_sma_100,dist_d1_trend_sma_200,dist_d1_trend_ema_8,dist_d1_trend_ema_21,dist_d1_trend_high_52w,dist_d1_trend_low_52w,dist_d1_trend_prev_day_high,dist_d1_trend_prev_day_low,dist_d1_trend_prev_week_high,dist_d1_trend_prev_week_low,dist_d1_trend_prev_month_high,dist_d1_trend_prev_month_low,dist_d1_ha_ha_open,dist_d1_ha_ha_high,dist_d1_ha_ha_low,dist_d1_ha_ha_close,dist_open_d1,dist_high_d1,dist_low_d1,dist_close_d1,d1_natr,target_reg_5m_logret,target_cls_5m,target_reg_30m_logret,target_cls_30m,target_reg_1h_logret,target_cls_1h,target_reg_2h_logret,target_cls_2h,target_reg_4h_logret,target_cls_4h,target_reg_1d_logret,target_cls_1d,target_reg_3d_logret,target_cls_3d,target_reg_5d_logret,target_cls_5d,target_reg_10d_logret,target_cls_10d
timestamp,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2024-01-05 09:30:00,2024-01-05 09:30:00,1.848887,3.256922,0.757790,1.807835,0.0,0.488454,0.488454,0.000424,0.000477,-1,BKNG,6.406676e+05,0.908591,6.406676e+05,0.908591,470.959991,467.049988,467.239990,467.540985,467.149994,467.489990,0.000321,-0.000214,0.155880,-27.759089,0.0,467.731110,467.360321,469.899475,453.025421,435.852814,470.601379,467.800262,3.842143,477.549988,378.760010,470.959991,467.049988,57.049286,0.245453,-0.480768,1.677598,0.722130,-0.586896,0.539663,1.748543,1.242346,0.849017,-0.634597,3.079767,0.305486,-1.0,0.817772,47.289265,25.626812,20.231369,BKNG,4,0.608761,-0.793353,0.0,1.000000e+00,-0.000081,0.000324,-9.640664e-04,0.007973,-0.010899,-4.238215e-04,0.000267,-0.003160,-0.000476,0.000076,0.000267,-0.003160,-0.000842,0.005076,-0.068853,-0.086157,-0.145900,0.015029,-0.002397,0.046540,-0.398848,0.017329,-0.004782,0.041816,0.011416,-0.090273,-0.201190,0.017744,0.017744,-0.010899,-0.002400,-0.006252,0.007973,-0.010899,-0.000424,0.016674,-0.000289,1,0.002168,1,0.001174,1,0.001101,1,-0.002987,1,0.001681,1,0.029555,2,0.028778,2,0.025563,1
2022-06-01 09:30:00,2022-06-01 09:30:00,-2.767515,-2.724167,0.006947,-19.463127,0.0,0.644367,0.644367,0.008394,-0.001662,1,AAL,7.425109e+05,0.750769,7.425109e+05,0.750769,416.459991,410.029999,413.100006,415.640015,415.049988,415.149994,0.006028,0.001060,0.699702,-2.419685,0.0,414.247894,415.426666,402.459991,425.185211,444.212708,405.722839,406.878296,9.896428,479.980011,380.540009,416.459991,410.029999,1.010271,-0.419691,-0.826581,-0.996480,-0.465672,0.452029,-0.231177,1.037304,0.974809,-0.660506,4.622047,1.746976,5.100154,1.0,0.341920,16.959574,26.067667,23.856974,AAL,2,0.608761,-0.793353,0.5,-8.660254e-01,-0.003589,-0.004058,2.540309e-08,0.011099,-0.028302,-8.324038e-03,0.003330,-0.003330,0.001665,-0.007081,0.003330,-0.007081,0.000416,-0.051360,-0.016792,-0.040676,0.017740,-0.048703,-0.044036,0.445061,-0.309650,0.010544,-0.037736,-0.010266,-0.121532,0.188679,-0.091565,-0.050605,0.011099,-0.050605,-0.010960,-0.018313,0.011099,-0.028302,-0.008324,0.056064,-0.026998,0,-0.027569,0,-0.043960,0,-0.046864,0,-0.049694,0,-0.041354,0,-0.107397,0,-0.075176,0,-0.341647,0
2006-01-10 09:30:00,2006-01-10 09:30:00,1.171099,NaN,0.000000,-16.547449,1.0,1.383584,1.383584,0.000000,0.000145,-1,BA,3.345840e+05,1.389487,3.345840e+05,1.389487,129.059998,128.380005,128.850006,128.410004,128.330002,128.389999,-0.003648,-0.000078,0.458417,-1.916013,0.0,128.731003,128.373337,126.747498,125.296799,121.492172,127.664017,126.780838,0.972143,129.059998,112.089996,129.059998,128.380005,1.136429,-5.100496,-2.761192,-3.328254,-1.403166,-4.365314,0.373345,-3.987986,-0.140247,-2.350868,0.377275,-1.357694,0.037786,-1.0,0.426166,16.710876,18.259706,25.749390,BA,1,0.608761,-0.793353,0.0,1.000000e+00,0.000054,0.000106,-4.848840e-05,0.008574,-0.002180,-3.548040e-08,0.000145,-0.000291,-0.000145,0.000160,0.000160,-0.000291,-0.000073,0.024895,-0.003720,-0.020724,-0.056073,0.017521,0.018522,0.052173,-0.280337,0.024560,0.003488,0.052173,0.019619,0.002471,-0.074262,0.018768,0.018768,-0.002180,0.003306,0.006830,0.008574,-0.002180,0.000000,0.016515,0.002323,2,0.000000,1,0.003627,2,0.000538,1,0.005941,1,0.004061,1,0.013568,1,-0.001018,1,-0.018185,1
2015-02-20 09:30:00,2015-02-20 09:30:00,-4.241734,-6.196772,0.087438,-20.924448,0.0,1.883499,1.883499,-0.006235,-0.004957,-1,KLAC,1.514710e+06,1.069181,1.514710e+06,1.069181,210.419998,209.240005,210.050003,209.649994,209.429993,209.479996,-0.002238,0.000477,0.094241,-8.569399,0.0,209.899094,209.553329,205.753494,204.638596,198.911072,209.148392,206.762482,2.040350,212.970001,181.309998,210.419998,209.240005,1.245357,-0.591168,-0.870883,-1.232758,-1.542506,-1.240909,-2.388910,-2.442644,-2.659396,-2.387393,-1.750610,-3.049047,-1.867272,1.0,0.290958,15.209001,25.787088,25.375040,KLAC,4,0.608761,-0.793353,0.5,8.660254e-01,0.003090,0.005180,1.505025e-03,0.011832,-0.006383,6.274377e-03,0.004982,-0.000467,0.004982,0.006287,0.006287,-0.000467,0.002374,-0.006165,0.042926,0.108797,0.113287,-0.004352,0.003999,0.311070,-0.062588,0.006850,-0.009341,-0.004204,-0.062588,0.311070,0.039078,-0.004915,0.011832,-0.006383,0.001880,-0.004204,0.011832,-0.006383,0.006274,0.019389,0.005589,2,0.002333,1,0.007167,2,0.013761,2,0.010069,2,0.011455,2,0.030512,2,0.019351,1,-0.024907,1
2023-04-13 09:30:00,2023-04-13 09:30:00,1.114965,4.254609,0.490219,-9.146677,0.0,1.155187,1.155187,0.008325,0.005029,1,APA,7.188437e+05,0.861294,7.188437e+05,0.861294,412.170013,407.440002,407.989990,409.350006,409.079987,409.239990,0.002941,-0.000122,0.206595,-27.247347,0.0,408.237396,409.206665,402.182495,402.388397,393.918945,408.780243,404.272400,4.180143,450.010010,348.109985,412.170013,407.440002,1.427857,1.190171,0.891283,0.319908,0.266068,1.278226,-0.137564,-0.314822,0.211894,-1.039782,-1.878569,0.272800,-0.741854,1.0,1.000000,21.651459,30.572660,18.835859,APA,3,0.608761,-0.793353,1.0,6.123234e-17,-0.004025,-0.005808,-1.751275e-03,0.009757,-0.010258,-8.256207e-03,0.002252,-0.007506,-0.005004,-0.007933,0.002252,-0.007933,-0.002564,-0.101789,-0.039284,0.043815,0.002431,-0.037840,-0.064462,0.299725,-0.245684,0.011258,-0.020766,-0.108974,-0.206655,0.101826,-0.072429,-0.022515,0.009757,-0.022515,-0.001188,0.004003,0.009757,-0.010258,-0.008256,0.035723,-0.009679,0,0.000500,1,0.005613,1,0.000250,1,0.007974,1,0.012432,1,-0.011196,1,-0.032419,1,-0.127936,0

In [4]:
import os
import pandas as pd

data_path = '/opt/rws/repos/RWS_LightGBM/data/reprocessed/final_merged_with_spy/ml_ready_with_targets'
tickers = [f for f in os.listdir(data_path) if f.endswith('.parquet')]

print(f"Scanning {len(tickers)} tickers...")

# 1. Get columns from the first ticker as a baseline
first_ticker = 'AAPL.parquet'
first_cols = set(pd.read_parquet(os.path.join(data_path, first_ticker)).columns)
common_columns = first_cols.copy()

# 2. Find the intersection (columns that exist in EVERY file)
diff_found = False
for ticker in tickers:
    # Use columns=[] to read metadata only (much faster)
    current_cols = set(pd.read_parquet(os.path.join(data_path, ticker)).columns)
    
    # Check if this ticker is missing anything from our baseline
    missing = common_columns - current_cols
    if missing:
        print(f"⚠️ {ticker} is missing {len(missing)} columns: {list(missing)}...")
        common_columns &= current_cols
        diff_found = True

if not diff_found:
    print("✅ All tickers have identical columns.")
else:
    print(f"\nSummary:")
    print(f"- Total unique columns in first file: {len(first_cols)}")
    print(f"- Total common columns across all files: {len(common_columns)}")
    print(f"- Columns to be excluded: {len(first_cols - common_columns)}")

Scanning 318 tickers...
⚠️ CRWV.parquet is missing 16 columns: ['dist_d1_trend_sma_100', 'dist_d1_trend_sma_200', 'dist_d1_trend_high_52w', 'dist_d1_trend_prev_week_low', 'dist_d1_trend_prev_day_low', 'dist_d1_trend_ema_21', 'dist_d1_trend_prev_week_high', 'dist_d1_trend_sma_20', 'd1_natr', 'dist_d1_trend_low_52w', 'dist_d1_trend_ema_8', 'dist_d1_trend_prev_day_high', 'd1_trend_atr_14', 'dist_d1_trend_prev_month_high', 'dist_d1_trend_sma_50', 'dist_d1_trend_prev_month_low']...
⚠️ GEV.parquet is missing 6 columns: ['d1_rrs_rrs_sec_25_sma', 'd1_rrs_rrs_sec_12', 'd1_rrs_rrs_sec_25', 'd1_rrs_rrs_sec_5', 'd1_rrs_rrs_sec_5_sma', 'd1_rrs_rrs_sec_12_sma']...
⚠️ CRCL.parquet is missing 8 columns: ['m5_vol_rel_vol', 'm5_vol_rel_cum_vol', 'd1_rrs_rrs_spy_25', 'd1_rrs_rrs_spy_12_sma', 'd1_rrs_rrs_spy_5', 'd1_rrs_rrs_spy_5_sma', 'd1_rrs_rrs_spy_25_sma', 'd1_rrs_rrs_spy_12']...

Summary:
- Total unique columns in first file: 115
- Total common columns across all files: 85
- Columns to be excluded: 30

In [11]:
# Assuming 'common_columns' is the set or list returned by your snippet
feature_columns = [c for c in sorted(list(common_columns)) 
                   if not c.startswith('target_') 
                   and c not in ['ticker', 'ticker_d1', 'time_weekday', 'time_sin', 'time_cos', 'month_sin', 'month_cos', 'm5_levels_chg_from_yest_close_pct']]
feature_columns

['d1_adx_adx',
 'd1_adx_minus_di',
 'd1_adx_plus_di',
 'd1_ha_ha_color',
 'd1_lrsi_laguerre_rsi_0.7',
 'dist_close_d1',
 'dist_d1_ha_ha_close',
 'dist_d1_ha_ha_high',
 'dist_d1_ha_ha_low',
 'dist_d1_ha_ha_open',
 'dist_high_d1',
 'dist_low_d1',
 'dist_m5_ha_ha_close',
 'dist_m5_ha_ha_high',
 'dist_m5_ha_ha_low',
 'dist_m5_ha_ha_open',
 'dist_m5_levels_hod',
 'dist_m5_levels_lod',
 'dist_m5_levels_session_open',
 'dist_m5_levels_yest_close',
 'dist_m5_levels_yest_high',
 'dist_m5_levels_yest_low',
 'dist_m5_ma_ema_3',
 'dist_m5_ma_ema_8',
 'dist_m5_ma_vwap',
 'dist_open_d1',
 'm5_ha_ha_color',
 'm5_levels_chg_from_open_pct',
 'm5_mom_lrsi',
 'm5_mom_squeeze_on',
 'm5_mom_tsi',
 'm5_rrs_rrs_sector',
 'm5_rrs_rrs_spy',
 'spy_d1_atr_14',
 'spy_d1_ema_21',
 'spy_d1_ema_8',
 'spy_d1_high_52w',
 'spy_d1_low_52w',
 'spy_d1_prev_day_high',
 'spy_d1_prev_day_low',
 'spy_d1_sma_20',
 'spy_d1_sma_200',
 'spy_d1_sma_50',
 'spy_m5_avg_cum_vol_50d',
 'spy_m5_avg_vol_50d',
 'spy_m5_chg_from_open_pct',
 'spy_m5_chg_from_yest_close_pct',
 'spy_m5_ema_8',
 'spy_m5_hod',
 'spy_m5_lod',
 'spy_m5_lrsi',
 'spy_m5_rel_cum_vol',
 'spy_m5_rel_vol',
 'spy_m5_session_open',
 'spy_m5_squeeze_on',
 'spy_m5_tsi',
 'spy_m5_vwap',
 'spy_m5_yest_close',
 'spy_m5_yest_high',
 'spy_m5_yest_low',
 'timestamp']

In [12]:
len(feature_columns)

61