In [1]:
import pandas as pd
from IPython.display import display

In [2]:
universe = pd.read_parquet("/home/patricsanchez/ElegantRL/data/walk_forward/universe_2025.parquet")
pd.options.display.max_columns = None
display(universe)

,timestamp,m5_mom_lrsi,m5_mom_tsi,m5_mom_squeeze_on,m5_vol_rel_vol,m5_vol_rel_cum_vol,m5_ha_ha_color,m5_ha_ha_flat_bottom,m5_ha_ha_flat_top,m5_ha_ha_body_pct,m5_ha_ha_wick_upper_pct,m5_ha_ha_wick_lower_pct,m5_ha_ha_doji,m5_ha_ha_size_ratio,m5_ha_ha_body_accel,m5_ha_ha_trend_score_6,m5_ha_ha_bull_power_6,m5_ha_ha_bear_power_6,m5_ha_ha_doji_freq_6,m5_ha_ha_motive_avg_6,m5_ha_ha_trend_score_12,m5_ha_ha_bull_power_12,m5_ha_ha_bear_power_12,m5_ha_ha_doji_freq_12,m5_ha_ha_motive_avg_12,m5_rrs_mom_5,m5_rrs_rrs_spy_5,m5_rrs_rrs_spy_5_sma,m5_rrs_vrrs_spy_5,m5_rrs_rrs_sec_5,m5_rrs_rrs_sec_5_sma,m5_rrs_vrrs_sec_5,m5_rrs_mom_12,m5_rrs_rrs_spy_12,m5_rrs_rrs_spy_12_sma,m5_rrs_vrrs_spy_12,m5_rrs_rrs_sec_12,m5_rrs_rrs_sec_12_sma,m5_rrs_vrrs_sec_12,m5_rrs_mom_25,m5_rrs_rrs_spy_25,m5_rrs_rrs_spy_25_sma,m5_rrs_vrrs_spy_25,m5_rrs_rrs_sec_25,m5_rrs_rrs_sec_25_sma,m5_rrs_vrrs_sec_25,m5_time_time_weekday,m5_time_time_month_sin,m5_time_time_month_cos,m5_time_time_day_sin,m5_time_time_day_cos,m5_time_time_mkt_open_min,m5_time_time_mkt_close_min,d1_rrs_mom_5,d1_rrs_rrs_spy_5,d1_rrs_rrs_spy_5_sma,d1_rrs_rrs_sec_5,d1_rrs_rrs_sec_5_sma,d1_rrs_mom_12,d1_rrs_rrs_spy_12,d1_rrs_rrs_spy_12_sma,d1_rrs_rrs_sec_12,d1_rrs_rrs_sec_12_sma,d1_rrs_mom_25,d1_rrs_rrs_spy_25,d1_rrs_rrs_spy_25_sma,d1_rrs_rrs_sec_25,d1_rrs_rrs_sec_25_sma,d1_ha_ha_color,d1_ha_ha_flat_bottom,d1_ha_ha_flat_top,d1_ha_ha_body_pct,d1_ha_ha_wick_upper_pct,d1_ha_ha_wick_lower_pct,d1_ha_ha_doji,d1_ha_ha_size_ratio,d1_ha_ha_body_accel,d1_ha_ha_trend_score_5,d1_ha_ha_bull_power_5,d1_ha_ha_bear_power_5,d1_ha_ha_doji_freq_5,d1_ha_ha_motive_avg_5,d1_ha_ha_trend_score_10,d1_ha_ha_bull_power_10,d1_ha_ha_bear_power_10,d1_ha_ha_doji_freq_10,d1_ha_ha_motive_avg_10,d1_lrsi_lrsi,d1_adx_adx,d1_adx_plus_di,d1_adx_minus_di,spy_m5_rel_vol,spy_m5_rel_cum_vol,spy_m5_chg_from_yest_close_pct,spy_m5_chg_from_open_pct,spy_m5_lrsi,spy_m5_ha_color,spy_m5_ha_flat_bottom,spy_m5_ha_flat_top,spy_m5_ha_body_pct,spy_m5_ha_wick_upper_pct,spy_m5_ha_wick_lower_pct,spy_m5_ha_doji,spy_m5_ha_size_ratio,spy_m5_ha_body_accel,spy_m5_ha_trend_score_6,spy_m5_ha_bull_power_6,spy_m5_ha_bear_power_6,spy_m5_ha_doji_freq_6,spy_m5_ha_motive_avg_6,spy_m5_ha_trend_score_12,spy_m5_ha_bull_power_12,spy_m5_ha_bear_power_12,spy_m5_ha_doji_freq_12,spy_m5_ha_motive_avg_12,spy_d1_ha_color,spy_d1_ha_flat_bottom,spy_d1_ha_flat_top,spy_d1_ha_body_pct,spy_d1_ha_wick_upper_pct,spy_d1_ha_wick_lower_pct,spy_d1_ha_doji,spy_d1_ha_size_ratio,spy_d1_ha_body_accel,spy_d1_ha_trend_score_5,spy_d1_ha_bull_power_5,spy_d1_ha_bear_power_5,spy_d1_ha_doji_freq_5,spy_d1_ha_motive_avg_5,spy_d1_ha_trend_score_10,spy_d1_ha_bull_power_10,spy_d1_ha_bear_power_10,spy_d1_ha_doji_freq_10,spy_d1_ha_motive_avg_10,d1_natr,natr_spy_d1_atr_14,dist_m5_ma_ema_3,dist_m5_ma_ema_8,dist_m5_ma_vwap,dist_m5_lvl_yest_high,dist_m5_lvl_yest_low,dist_m5_lvl_yest_close,dist_m5_lvl_hod,dist_m5_lvl_lod,dist_m5_lvl_session_open,dist_open_d1,dist_high_d1,dist_low_d1,dist_close_d1,dist_d1_trend_open,dist_d1_trend_high,dist_d1_trend_low,dist_d1_trend_close,dist_d1_trend_sma_20,dist_d1_trend_sma_50,dist_d1_trend_sma_100,dist_d1_trend_sma_200,dist_d1_trend_ema_8,dist_d1_trend_ema_21,dist_d1_trend_high_52w,dist_d1_trend_low_52w,dist_d1_trend_prev_day_high,dist_d1_trend_prev_day_low,dist_d1_trend_prev_week_high,dist_d1_trend_prev_week_low,dist_d1_trend_prev_month_high,dist_d1_trend_prev_month_low,dist_spy_m5_close,dist_spy_m5_yest_high,dist_spy_m5_yest_low,dist_spy_m5_yest_close,dist_spy_m5_hod,dist_spy_m5_lod,dist_spy_m5_session_open,dist_spy_m5_ema_8,dist_spy_m5_vwap,dist_spy_d1_close,dist_spy_d1_sma_20,dist_spy_d1_sma_50,dist_spy_d1_sma_200,dist_spy_d1_ema_8,dist_spy_d1_ema_21,dist_spy_d1_high_52w,dist_spy_d1_low_52w,dist_spy_d1_prev_day_high,dist_spy_d1_prev_day_low,target_reg_5m_logret,target_cls_5m,target_reg_30m_logret,target_cls_30m,target_reg_1h_logret,target_cls_1h,target_reg_2h_logret,target_cls_2h,target_reg_4h_logret,target_cls_4h,target_reg_1d_logret,target_cls_1d,target_reg_3d_logret,target_cls_3d,target_reg_5d_logret,target_cls_5d,target_reg_10d_logret,target_cls_10d,ticker
0,2025-01-02 09:30:00,-0.181558,-0.043934,1.0,-1.034849,-1.034849,1.0,1.0,-1.0,0.591571,0.408429,0.000000,-1.0,4.743788,0.228996,0.333333,0.333333,0.166667,0.333333,0.390402,0.166667,0.333333,0.166667,0.166667,0.424379,0.018953,-0.311805,0.381955,-0.152332,-1.534335,0.022731,-0.767670,-0.002288,-1.410815,-0.862858,-0.703082,-2.262342,-0.907952,-1.168402,0.003174,-1.653975,-0.419071,-0.831012,-2.478849,-0.710232,-1.296478,0.5,0.000000e+00,1.0,0.608761,-0.793353,-1.0,1.0,-0.001642,0.450614,-0.077174,0.270662,0.257122,-0.019473,0.749966,0.503582,0.998819,1.864464,0.000005,1.001793,-0.362640,3.169054,1.198786,-1.0,-1.0,-1.0,0.013209,0.591845,0.394947,1.0,0.800000,-0.314308,0.2,0.2,0.0,0.4,0.283927,-0.4,0.1,0.2,0.2,0.381291,-1.000000,-2.743294,-1.401037,0.049151,1.108873,0.470543,-0.003095,-0.006315,0.628105,-1.0,-1.0,-1.0,0.344423,0.180787,0.474790,-1.0,0.650629,0.034020,-0.333333,0.0,0.166667,0.166667,0.293280,0.000000,0.333333,0.083333,0.166667,0.389191,-1.0,-1.0,1.0,0.571387,0.000000,0.428613,-1.0,0.648534,-0.129894,-0.2,0.4,0.4,0.0,0.598888,-0.4,0.2,0.4,0.0,0.547180,0.018859,0.013351,-0.000570,-0.001072,0.001922,0.010972,-0.003013,-0.000707,0.005765,0.000000,0.005765,0.002789,0.010972,-0.003013,-0.000707,0.002789,0.010972,-0.003013,-0.000707,0.023978,0.006454,0.027293,0.028903,0.006334,0.012967,0.155577,-0.076431,0.008592,-0.008889,0.040934,-0.020939,0.064232,-0.071001,0.0,0.009485,-0.003020,0.003105,0.007608,-0.003002,0.006355,-0.000147,0.000718,0.000000,0.022792,0.011389,-0.055424,0.012096,0.016834,0.039049,-0.204289,0.009485,-0.003020,0.006709,2,0.007374,2,0.000000,1,-0.007406,0,-0.009830,0,-0.007504,1,0.012603,1,0.022179,2,0.072821,2,A
1,2025-01-02 09:30:00,0.313329,0.101025,-1.0,0.899024,0.899024,1.0,1.0,-1.0,0.685175,0.314825,0.000000,-1.0,4.912777,0.201099,-0.333333,0.166667,0.500000,0.166667,0.519478,0.166667,0.333333,0.250000,0.166667,0.464507,0.028466,0.163420,-0.451289,0.304477,-1.091858,-0.805413,-1.958831,0.032653,0.296564,-0.351384,0.551430,-0.687550,-0.397676,-1.262419,0.039373,0.091378,1.099974,0.170356,-0.898552,0.815883,-1.632045,0.5,0.000000e+00,1.0,0.608761,-0.793353,-1.0,1.0,-0.005179,0.274718,-0.114906,0.094071,0.219461,-0.011403,1.138823,-0.694992,1.379245,0.748413,-0.046522,-1.281626,-1.465944,1.376007,0.075597,-1.0,-1.0,-1.0,0.023269,0.583114,0.393617,1.0,0.662557,-0.592589,-0.2,0.2,0.4,0.2,0.408274,-0.4,0.2,0.4,0.1,0.436649,-1.000000,2.178819,-2.617341,1.391677,1.108873,0.470543,-0.003095,-0.006315,0.628105,-1.0,-1.0,-1.0,0.344423,0.180787,0.474790,-1.0,0.650629,0.034020,-0.333333,0.0,0.166667,0.166667,0.293280,0.000000,0.333333,0.083333,0.166667,0.389191,-1.0,-1.0,1.0,0.571387,0.000000,0.428613,-1.0,0.648534,-0.129894,-0.2,0.4,0.4,0.0,0.598888,-0.4,0.2,0.4,0.0,0.547180,0.033460,0.013351,-0.008366,-0.011891,-0.004266,-0.006117,-0.030587,-0.016530,0.000609,-0.013406,-0.006508,-0.030587,-0.006117,-0.030587,-0.016530,-0.030587,-0.006117,-0.030587,-0.016530,0.039503,0.093562,0.001499,-0.015691,-0.009746,0.031901,0.243525,-0.352857,-0.017832,-0.045946,0.023298,-0.055577,0.243525,0.044123,0.0,0.009485,-0.003020,0.003105,0.007608,-0.003002,0.006355,-0.000147,0.000718,0.000000,0.022792,0.011389,-0.055424,0.012096,0.016834,0.039049,-0.204289,0.009485,-0.003020,0.002210,2,0.011003,2,0.003638,1,0.010233,2,-0.009547,1,-0.011125,1,-0.053605,0,-0.071338,0,0.017930,1,AA
2,2025-01-02 09:30:00,-0.214876,-0.068973,-1.0,-0.738977,-0.738977,-1.0,-1.0,-1.0,0.394343,0.086427,0.519231,-1.0,4.482759,0.031271,-0.666667,0.000000,0.166667,0.166667,0.389288,0.166667,0.166667,0.083333,0.250000,0.346649,-0.012798,-1.813302,-0.666500,-1.118985,-0.162049,-0.093137,-0.097115,-0.026758,-2.444961,-0.329986,-1.549315,-0.777292,0.028141,-0.468157,-0.018009,-2.523314,-0.002927,-1.605446,-0.552020,0.567333,-0.331617,0.5,0.000000e+00,1.0,0.608761,-0.793353,-1.0,1.0,0.002899,0.674747,0.301891,0.671224,0.608862,0.001706,1.738913,1.886315,1.167578,0.041955,0.051618,3.082159,1.404802,1.009286,-0.963859,1.0,1.0,-1.0,0.529361,0.470639,0.000000,-1.0,0.766016,0.070777,1.0,0.4,0.0,0.0,0.446570,0.4,0.3,0.1,0.1,0.395204,1.000000,3.795621,2.013013,-2.982020,1.108873,0.470543,-0.003095,-0.006315,0.628105,-1.0,-1.0,-1.0,0.344423,0.180787,0.474790,-1.0,0.650629,0.034020,-0.333333,0.0,0.166667,0.166667,0.293280,0.000000,0.333333,0.083333,0.166667,0.389191,-1.0,-1.0,1.0,0.571387,0.000000,0.428613,-1.0,0.648534,-0.129894,-0.2,0.4,0.4,0.0,0.598888,-0.4,0.2,0.4,0.0,0.547180,0.029147,0.013351,0.001923,0.003474,0.000576,0.022396,-0.000576,0.004032,0.004608,-0.002880,0.002304,0.015553,0.022396,-0.000576,0.004032,0.015553,0.022396,-0.000576,0.004032,-0.026612,-0.131116,-0.249942,-0.263381,-0.005952,-0.041176,0.048675,-0.477535,0.021313,-0.012097,-0.004608,-0.065668,-0.128744,-0.255760,0.0,0.009485,-0.003020,0.003105,0.007608,-0.003002,0.006355,-0.000147,0.000718,0.000000,0.022792,0.011389,-0.055424,0.012096,0.016834,0.039049,-0.204289,0.009485,-0.003020,-0.002307,0,0.010600,2,-0.001441,1,-0.011588,0,-0.026500,0,-0.020955,0,0.014866,1,0.015717,1,0.050818,2,AAL
3,2025-01-02 09:30:00,-0.113489,-0.072177,-1.0,0.031807,0.031807,-1.0,-1.0,1.0,0.778403,0.000000,0.221597,-1.0,2.956096,0.537096,-0.666667,0.000000,0.166667,0.166667,0.330112,0.000000,0.166667,0.083333,0.083333,0.378458,-0.041991,-2.931074,-0.550806,-2.979795,-2.813252,-0.465770,-2.861365,-0.026484,-2.434501,0.046856,-2.479477,-2.409602,-0.088032,-2.454314,-0.016009,-2.448038,-0.085341,-2.493154,-2.497659,0.091106,-2.543273,0.5,0.000000e+00,1.0,0.608761,-0.793353,-1.0,1.0,-0.009793,0.044289,0.234284,0.140388,0.151829,0.008377,2.025043,2.395162,1.125242,1.522678,0.059413,3.312301,1.544888,2.711501,1.667899,-1.0,-1.0,1.0,0.593346,0.000000,0.406654,-1.0,0.851063,-0.161364,-0.2,0.4,0.4,0.2,0.577512,0.2,0.4,0.2,0.2,0.475051,0.919419,3.320023,0.323144,-1.566177,1.108873,0.470543,-0.003095,-0.006315,0.628105,-1.0,-1.0,-1.0,0.344423,0.180787,0.474790,-1.0,0.650629,0.034020,-0.333333,0.0,0.166667,0.166667,0.293280,0.000000,0.333333,0.083333,0.166667,0.389191,-1.0,-1.0,1.0,0.571387,0.000000,0.428613,-1.0,0.648534,-0.129894,-0.2,0.4,0.4,0.0,0.598888,-0.4,0.2,0.4,0.0,0.547180,0.017929,0.013351,0.004499,0.007145,0.000860,0.020550,0.005037,0.009630,0.003264,-0.000685,0.003022,0.017165,0.020550,0.005037,0.009630,0.017165,0.020550,0.005037,0.009630,0.006538,-0.042623,-0.067061,-0.140160,0.020162,0.002193,0.048030,-0.338887,0.021436,0.010355,0.027480,-0.010033,-0.041422,-0.114715,0.0,0.009485,-0.003020,0.003105,0.007608,-0.003002,0.006355,-0.000147,0.000718,0.000000,0.022792,0.011389,-0.055424,0.012096,0.016834,0.039049,-0.204289,0.009485,-0.003020,-0.009505,0,-0.006002,0,-0.011672,0,-0.012896,0,-0.023111,0,-0.017929,0,-0.013100,1,-0.025217,0,-0.078295,0,AAPL
4,2025-01-02 09:30:00,0.498923,0.214714,-1.0,0.325945,0.325945,1.0,1.0,-1.0,0.754031,0.245969,0.000000,-1.0,1.948080,0.738427,0.000000,0.333333,0.000000,0.500000,0.315848,0.000000,0.250000,0.083333,0.250000,0.341165,0.050982,1.261411,1.103997,1.562029,-0.918946,-0.086163,-1.144483,0.040308,0.675485,-0.009076,0.843770,-1.000675,-0.231834,-1.244775,0.044325,0.338459,0.983913,0.423884,-1.291185,0.221842,-1.597966,0.5,0.000000e+00,1.0,0.608761,-0.793353,-1.0,1.0,-0.004733,0.296929,0.282003,0.073887,0.344852,0.008857,2.045099,0.715265,1.624180,1.864316,-0.006434,0.689123,-1.671507,1.982124,0.991306,-1.0,-1.0,-1.0,0.335774,0.241049,0.423177,-1.0,0.704136,-0.294766,0.2,0.4,0.2,0.2,0.495395,0.4,0.3,0.1,0.2,0.415741,0.128219,-2.262830,-0.430433,0.411159,1.108873,0.470543,-0.003095,-0.006315,0.628105,-1.0,-1.0,-1.0,0.344423,0.180787,0.474790,-1.0,0.650629,0.034020,-0.333333,0.0,0.166667,0.166667,0.293280,0.000000,0.333333,0.083333,0.166667,0.389191,-1.0,-1.0,1.0,0.571387,0.000000,0.428613,-1.0,0.648534,-0.129894,-0.2,0.4,0.4,0.0,0.598888,-0.4,0.2,0.4,0.0,0.547180,0.018339,0.013351,-0.005332,-0.008331,-0.001089,-0.006425,-0.017152,-0.012124,0.001453,-0.004721,-0.001844,-0.014749,-0.006425,-0.017152,-0.012124,-0.014749,-0.006425,-0.017152,-0.012124,-0.016900,0.012026,0.048785,-0.001147,-0.011779,-0.011652,0.158277,-0.141963,-0.009218,-0.019442,-0.012235,-0.049053,0.151740,-0.084809,0.0,0.009485,-0.003020,0.003105,0.007608,-0.003002,0.006355,-0.000147,0.000718,0.000000,0.022792,0.011389,-0.055424,0.012096,0.016834,0.039049,-0.204289,0.009485,-0.003020,0.001173,2,-0.002954,0,-0.002853,1,-0.002517,1,-0.002237,1,0.002511,1,0.005016,1,-0.004311,1,-0.032652,0,ABBV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5477730,2025-07-25 16:00:00,-1.000000,-0.060618,-1.0,-0.294996,-0.575905,1.0,-1.0,-1.0,0.034854,0.602273,0.362873,1.0,0.647059,-0.069075,0.000000,0.000000,0.166667,0.333333,0.238703,-0.166667,0.000000,0.250000,0.166667,0.291003,0.007072,1.328588,0.562724,1.091662,1.913404,0.821115,1.586470,-0.006718,0.348938,-0.721143,0.284566,1.473582,-0.366834,1.213105,-0.026817,-0.514245,-0.990700,-0.419646,0.070664,-0.098997,0.057597,1.0,1.224647e-16,-1.0,-0.866025,-0.500000,1.0,-1.0,0.033449,0.949318,1.125972,1.559946,1.340279,0.037005,0.412581,-0.145432,1.008766,-0.094553,0.059469,-0.360448,-0.279340,-0.031840,-0.853079,1.0,1.0,-1.0,0.586704,0.413296,0.000000,-1.0,0.813624,-0.202410,1.0,1.0,0.0,0.0,0.773065,0.4,0.6,0.1,0.3,0.523721,0.723993,0.906471,3.218333,-2.987170,0.217659,-0.421747,0.003862,0.002724,-0.241341,-1.0,-1.0,1.0,0.524985,0.000000,0.475015,-1.0,2.251868,0.144199,-0.666667,0.0,0.333333,0.166667,0.331387,-0.166667,0.166667,0.166667,0.166667,0.378541,1.0,1.0,-1.0,0.760375,0.239625,0.000000,-1.0,0.800603,0.153431,1.0,0.8,0.0,0.0,0.561712,0.6,0.5,0.0,0.1,0.403947,0.034053,0.006974,-0.000087,0.000031,-0.003299,0.004830,-0.019074,-0.012014,0.004211,-0.022418,-0.012200,-0.016039,0.004830,-0.019074,-0.012014,-0.016039,0.004830,-0.019074,-0.012014,-0.127347,-0.194227,-0.250522,-0.111065,-0.061667,-0.118050,0.229378,-0.451697,-0.004706,-0.028363,-0.120882,-0.196805,-0.218355,-0.451697,0.0,-0.001005,-0.004397,-0.003847,0.001240,-0.003062,-0.002717,0.000659,-0.000532,-0.003847,-0.020701,-0.048072,-0.078661,-0.011785,-0.023444,-0.001005,-0.243393,-0.002183,-0.011087,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,XYZ
5477731,2025-07-25 16:00:00,0.908827,0.404608,-1.0,-0.880192,-0.671795,1.0,-1.0,-1.0,0.201734,0.546296,0.251970,-1.0,0.596440,-0.464150,0.666667,0.500000,0.000000,0.000000,0.387893,0.333333,0.500000,0.083333,0.166667,0.389874,0.031940,2.392123,1.919859,1.378506,1.066858,1.111735,0.585958,0.031872,2.133291,1.723418,1.213476,1.000089,1.487089,0.548552,0.061966,3.276734,1.584260,2.011026,2.702317,2.785444,1.586268,1.0,1.224647e-16,-1.0,-0.866025,-0.500000,1.0,-1.0,-0.008412,-1.113155,-0.575787,-0.967865,-0.677778,-0.015137,-2.062891,-1.034600,-1.679991,-0.681148,0.024410,-1.996442,-1.658632,-0.858409,-0.406255,-1.0,-1.0,-1.0,0.502200,0.190597,0.307203,-1.0,1.180000,0.147391,-0.2,0.2,0.0,0.2,0.357755,-0.4,0.1,0.2,0.1,0.409172,-0.760875,-2.007779,-1.004134,-0.328473,0.217659,-0.421747,0.003862,0.002724,-0.241341,-1.0,-1.0,1.0,0.524985,0.000000,0.475015,-1.0,2.251868,0.144199,-0.666667,0.0,0.333333,0.166667,0.331387,-0.166667,0.166667,0.166667,0.166667,0.378541,1.0,1.0,-1.0,0.760375,0.239625,0.000000,-1.0,0.800603,0.153431,1.0,0.8,0.0,0.0,0.561712,0.6,0.5,0.0,0.1,0.403947,0.017850,0.006974,0.000350,-0.000410,-0.002704,0.010157,-0.005930,-0.005930,0.002522,-0.010975,-0.005521,-0.002249,0.010157,-0.005930,-0.005930,-0.002249,0.010157,-0.005930,-0.005930,0.012615,-0.005089,0.014365,-0.029898,0.004356,0.004350,0.113156,-0.167485,0.015678,0.002045,0.044410,0.011384,0.027744,-0.027783,0.0,-0.001005,-0.004397,-0.003847,0.001240,-0.003062,-0.002717,0.000659,-0.000532,-0.003847,-0.020701,-0.048072,-0.078661,-0.011785,-0.023444,-0.001005,-0.243393,-0.002183,-0.011087,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,YUM
5477732,2025-07-25 16:00:00,0.913137,0.362119,-1.0,-0.841671,-1.105184,-1.0,-1.0,1.0,0.384566,0.000000,0.615434,-1.0,2.301900,0.072433,0.000000,0.333333,0.333333,0.000000,0.502987,0.500000,0.666667,0.166667,0.000000,0.632519,-0.017928,0.111273,0.601153,0.062097,-0.380286,0.056827,-0.212481,0.022172,1.720795,2.191614,0.987890,0.313820,1.427921,0.175269,0.039630,2.544533,1.023085,1.516625,0.580659,0.168892,0.325015,1.0,1.224647e-16,-1.0,-0.866025,-0.500000,1.0,-1.0,0.008730,-0.274740,-0.403953,-0.388878,0.323136,0.016768,-0.595468,-0.633380,0.629106,0.670894,0.035257,-1.521861,-1.886325,1.085745,-0.129229,1.0,1.0,-1.0,0.714889,0.285111,0.000000,-1.0,0.574235,-0.055175,0.6,0.4,0.0,0.2,0.451794,0.0,0.2,0.0,0.2,0.318141,0.988723,-0.707160,0.209115,-2.906080,0.217659,-0.421747,0.003862,0.002724,-0.241341,-1.0,-1.0,1.0,0.524985,0.000000,0.475015,-1.0,2.251868,0.144199,-0.666667,0.0,0.333333,0.166667,0.331387,-0.166667,0.166667,0.166667,0.166667,0.378541,1.0,1.0,-1.0,0.760375,0.239625,0.000000,-1.0,0.800603,0.153431,1.0,0.8,0.0,0.0,0.561712,0.6,0.5,0.0,0.1,0.403947,0.022777,0.006974,0.000362,0.000534,-0.003040,0.002255,-0.007893,-0.006971,0.002153,-0.011565,-0.007893,-0.003075,0.002255,-0.007893,-0.006971,-0.003075,0.002255,-0.007893,-0.006971,-0.036749,-0.042144,0.014507,0.054191,-0.022231,-0.033153,0.196412,-0.085187,0.003792,-0.017171,-0.006458,-0.055561,0.058637,-0.078216,0.0,-0.001005,-0.004397,-0.003847,0.001240,-0.003062,-0.002717,0.000659,-0.000532,-0.003847,-0.020701,-0.048072,-0.078661,-0.011785,-0.023444,-0.001005,-0.243393,-0.002183,-0.011087,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,ZBH
5477733,2025-07-25 16:00:00,-0.387273,-0.154959,-1.0,-1.257218,-1.624174,-1.0,-1.0,1.0,0.791012,0.000000,0.208988,-1.0,0.524151,-0.008881,-0.333333,0.333333,0.500000,0.000000,0.628067,-0.500000,0.166667,0.500000,0.000000,0.511708,-0.047558,-1.336942,-0.164793,-0.570744,-0.710670,0.098636,-0.298978,-0.046908,-1.601566,-0.307361,-0.690021,-0.489298,0.050961,-0.205240,-0.042594,-1.276052,-1.696696,-0.543743,-0.713256,-0.853326,-0.300079,1.0,1.224647e-16,-1.0,-0.866025,-0.500000,1.0,-1.0,-0.002717,-0.839345,-0.815948,-0.194507,-0.592282,-0.030277,-2.649865,-2.194547,-2.183931,-2.147713,-0.022569,-3.563343,-0.326626,-3.393605,-0.904160,-1.0,-1.0,-1.0,0.349807,0.111563,0.538630,-1.0,0.656812,-0.179289,-0.6,0.0,0.2,0.0,0.330859,-0.8,0.0,0.6,0.0,0.511769,-1.000000,2.364636,-2.845498,0.061559,0.217659,-0.421747,0.003862,0.002724,-0.241341,-1.0,-1.0,1.0,0.524985,0.000000,0.475015,-1.0,2.251868,0.144199,-0.666667,0.0,0.333333,0.166667,0.331387,-0.166667,0.166667,0.166667,0.166667,0.378541,1.0,1.0,-1.0,0.760375,0.239625,0.000000,-1.0,0.800603,0.153431,1.0,0.8,0.0,0.0,0.561712,0.6,0.5,0.0,0.1,0.403947,0.026819,0.006974,0.000693,0.002458,0.002188,0.000524,-0.017454,-0.006587,0.010919,-0.007670,-0.006779,-0.007565,0.000524,-0.017454,-0.006587,-0.007565,0.000524,-0.017454,-0.006587,0.046395,0.007621,-0.135609,-0.225422,0.006138,0.025324,0.112776,-0.463808,0.000436,-0.021612,0.112776,0.009836,-0.033877,-0.209095,0.0,-0.001005,-0.004397,-0.003847,0.001240,-0.003062,-0.002717,0.000659,-0.000532,-0.003847,-0.020701,-0.048072,-0.078661,-0.011785,-0.023444,-0.001005,-0.243393,-0.002183,-0.011087,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,NaN,1,ZS

In [4]:
pd.set_option('display.max_rows', None)
display(universe.describe().T)

,count,mean,min,25%,50%,75%,max,std
timestamp,5477735,2025-04-15 05:35:40.462528,2025-01-02 09:30:00,2025-02-24 15:30:00,2025-04-14 14:40:00,2025-06-04 14:15:00,2025-07-25 16:00:00,NaN
m5_mom_lrsi,5477735.0,0.037831,-1.0,-0.789179,0.075696,0.903693,1.0,0.780948
m5_mom_tsi,5477735.0,0.010739,-0.932743,-0.131226,0.013992,0.156615,0.943737,0.218918
m5_mom_squeeze_on,5477735.0,-0.644986,-1.0,-1.0,-1.0,-1.0,1.0,0.764194
m5_vol_rel_vol,5477735.0,-0.380213,-15.143374,-1.077939,-0.398091,0.311112,6.643856,1.155246
m5_vol_rel_cum_vol,5477735.0,-0.165441,-11.360528,-0.690595,-0.227575,0.287166,6.38042,0.79694
m5_ha_ha_color,5477735.0,0.023081,-1.0,-1.0,1.0,1.0,1.0,0.999734
m5_ha_ha_flat_bottom,5477735.0,-0.475624,-1.0,-1.0,-1.0,1.0,1.0,0.879649
m5_ha_ha_flat_top,5477735.0,-0.508649,-1.0,-1.0,-1.0,-1.0,1.0,0.860974
m5_ha_ha_body_pct,5477735.0,0.437752,0.0,0.234685,0.471342,0.628145,1.0,0.236083
m5_ha_ha_wick_upper_pct,5477735.0,0.283546,0.0,0.004108,0.326446,0.461034,0.75,0.209549
m5_ha_ha_wick_lower_pct,5477735.0,0.278702,0.0,0.0,0.320251,0.462419,0.75,0.21326
m5_ha_ha_doji,5477735.0,-0.784612,-1.0,-1.0,-1.0,-1.0,1.0,0.619987
m5_ha_ha_size_ratio,5477735.0,1.146064,0.000028,0.726744,0.973097,1.330258,10.0,0.789887
m5_ha_ha_body_accel,5477735.0,0.000001,-0.999973,-0.1844,0.003827,0.191674,0.999989,0.289895
m5_ha_ha_trend_score_6,5477735.0,0.023064,-1.0,-0.333333,0.0,0.666667,1.0,0.619103
m5_ha_ha_bull_power_6,5477735.0,0.262178,0.0,0.0,0.166667,0.5,1.0,0.257162
m5_ha_ha_bear_power_6,5477735.0,0.245667,0.0,0.0,0.166667,0.333333,1.0,0.252584
m5_ha_ha_doji_freq_6,5477735.0,0.107705,0.0,0.0,0.0,0.166667,1.0,0.131761
m5_ha_ha_motive_avg_6,5477735.0,0.437744,0.001078,0.352742,0.435471,0.519859,1.0,0.121441
m5_ha_ha_trend_score_12,5477735.0,0.023057,-1.0,-0.333333,0.0,0.333333,1.0,0.466185
m5_ha_ha_bull_power_12,5477735.0,0.262167,0.0,0.083333,0.25,0.416667,1.0,0.192546
m5_ha_ha_bear_power_12,5477735.0,0.245655,0.0,0.083333,0.25,0.333333,1.0,0.189833
m5_ha_ha_doji_freq_12,5477735.0,0.107714,0.0,0.0,0.083333,0.166667,0.916667,0.094274
m5_ha_ha_motive_avg_12,5477735.0,0.437732,0.031704,0.37543,0.435297,0.496531,1.0,0.091953
m5_rrs_mom_5,5477735.0,0.000173,-0.177647,-0.00918,0.000331,0.009683,0.175348,0.017304
m5_rrs_rrs_spy_5,5477735.0,-0.006506,-4.863482,-0.453878,-0.00805,0.440408,4.88276,0.808834
m5_rrs_rrs_spy_5_sma,5477735.0,-0.006788,-4.823287,-0.37287,-0.007862,0.359349,4.832974,0.677207
m5_rrs_vrrs_spy_5,5477735.0,0.005778,-5.0,-0.317233,-0.004202,0.316415,5.0,1.006431
m5_rrs_rrs_sec_5,5365477.0,-0.002309,-4.889269,-0.420249,-0.00692,0.410739,4.863911,0.765551
m5_rrs_rrs_sec_5_sma,5363005.0,-0.002451,-4.849103,-0.344494,-0.006795,0.334895,4.783886,0.637772
m5_rrs_vrrs_sec_5,5365477.0,0.008595,-5.0,-0.294369,-0.003729,0.295546,5.0,0.962457
m5_rrs_mom_12,5477735.0,0.000413,-0.208496,-0.014898,0.000727,0.015997,0.187581,0.026723
m5_rrs_rrs_spy_12,5477735.0,-0.016212,-4.9337,-0.731558,-0.016674,0.698414,4.924024,1.202274
m5_rrs_rrs_spy_12_sma,5477735.0,-0.017196,-4.896911,-0.60552,-0.017892,0.570708,4.867597,1.012889
m5_rrs_vrrs_spy_12,5477735.0,0.00011,-5.0,-0.513787,-0.008756,0.500521,5.0,1.367938
m5_rrs_rrs_sec_12,5365477.0,-0.005814,-4.918897,-0.671392,-0.012024,0.652739,4.909177,1.13619
m5_rrs_rrs_sec_12_sma,5360253.0,-0.006308,-4.816371,-0.552144,-0.012501,0.533104,4.825744,0.95244
m5_rrs_vrrs_sec_12,5365477.0,0.008692,-5.0,-0.47123,-0.006415,0.470553,5.0,1.306749
m5_rrs_mom_25,5477735.0,0.000864,-0.242504,-0.02308,0.001347,0.025104,0.216942,0.03868
m5_rrs_rrs_spy_25,5477735.0,-0.03368,-4.98101,-1.115357,-0.030602,1.044637,4.977039,1.646942
m5_rrs_rrs_spy_25_sma,5477735.0,-0.035153,-4.944333,-0.930025,-0.03018,0.855884,4.873763,1.40728
m5_rrs_vrrs_spy_25,5477735.0,-0.010085,-5.0,-0.784134,-0.016046,0.748856,5.0,1.739297
m5_rrs_rrs_sec_25,5365477.0,-0.011812,-4.954025,-1.013732,-0.017995,0.983663,4.974165,1.560674
m5_rrs_rrs_sec_25_sma,5355222.0,-0.012539,-4.893665,-0.839116,-0.018299,0.807951,4.868251,1.327487
m5_rrs_vrrs_sec_25,5365477.0,0.007544,-5.0,-0.712692,-0.009575,0.707876,5.0,1.665945
m5_time_time_weekday,5477735.0,0.009506,-1.0,-0.5,0.0,0.5,1.0,0.698556
m5_time_time_month_sin,5477735.0,0.550542,0.0,0.0,0.5,0.866025,1.0,0.377817
m5_time_time_month_cos,5477735.0,0.01087,-1.0,-0.866025,0.0,0.866025,1.0,0.744339
m5_time_time_day_sin,5477735.0,-0.170863,-0.866025,-0.59131,-0.19509,0.237686,0.608761,0.453474
m5_time_time_day_cos,5477735.0,-0.863983,-1.0,-0.976296,-0.906308,-0.793353,-0.5,0.136752
m5_time_time_mkt_open_min,5477735.0,-0.00121,-1.0,-0.512821,0.0,0.512821,1.0,0.584821
m5_time_time_mkt_close_min,5477735.0,0.00121,-1.0,-0.512821,0.0,0.512821,1.0,0.584821
d1_rrs_mom_5,5477735.0,0.001093,-0.104372,-0.008303,0.001697,0.01107,0.086879,0.016
d1_rrs_rrs_spy_5,5477735.0,0.004522,-3.824581,-0.496643,-0.012669,0.474456,3.333147,0.799688
d1_rrs_rrs_spy_5_sma,5477735.0,0.00785,-3.461232,-0.40321,-0.01255,0.387349,2.781077,0.662773
d1_rrs_rrs_sec_5,5368364.0,0.011956,-3.76968,-0.425548,-0.002447,0.432435,3.249826,0.724995
d1_rrs_rrs_sec_5_sma,5368364.0,0.015774,-3.344597,-0.342899,0.002339,0.358878,2.787528,0.594105
d1_rrs_mom_12,5477735.0,0.002249,-0.10395,-0.013667,0.002891,0.01855,0.10451,0.024508
d1_rrs_rrs_spy_12,5477735.0,0.035403,-4.283558,-0.78785,0.007294,0.820798,4.165975,1.213634
d1_rrs_rrs_spy_12_sma,5477735.0,0.084832,-3.85799,-0.607141,0.085591,0.737343,3.70978,1.025041
d1_rrs_rrs_sec_12,5368364.0,0.045328,-4.240651,-0.648425,0.0303,0.728797,4.232751,1.077198
d1_rrs_rrs_sec_12_sma,5368364.0,0.075556,-3.827842,-0.510383,0.067866,0.637768,3.651267,0.910044
d1_rrs_mom_25,5477735.0,0.002474,-0.140708,-0.022519,0.001889,0.027233,0.16376,0.035634
d1_rrs_rrs_spy_25,5477735.0,0.15825,-4.79953,-1.117178,0.203475,1.400955,4.655096,1.71724
d1_rrs_rrs_spy_25_sma,5477735.0,0.236175,-4.313112,-0.790741,0.257034,1.243417,4.26437,1.439607
d1_rrs_rrs_sec_25,5368364.0,0.147015,-4.533177,-0.914315,0.148015,1.209376,4.708519,1.536339
d1_rrs_rrs_sec_25_sma,5368364.0,0.196315,-4.179609,-0.67935,0.198128,1.096925,4.265771,1.324275
d1_ha_ha_color,5477735.0,0.105509,-1.0,-1.0,1.0,1.0,1.0,0.994418
d1_ha_ha_flat_bottom,5477735.0,-0.392741,-1.0,-1.0,-1.0,1.0,1.0,0.919649
d1_ha_ha_flat_top,5477735.0,-0.539383,-1.0,-1.0,-1.0,-1.0,1.0,0.84206
d1_ha_ha_body_pct,5477735.0,0.451331,0.000027,0.248928,0.497172,0.645834,0.9804,0.23439
d1_ha_ha_wick_upper_pct,5477735.0,0.287541,0.0,0.053097,0.330222,0.45601,0.738494,0.201147
d1_ha_ha_wick_lower_pct,5477735.0,0.261128,0.0,0.0,0.29309,0.454243,0.748141,0.215027
d1_ha_ha_doji,5477735.0,-0.797499,-1.0,-1.0,-1.0,-1.0,1.0,0.603321
d1_ha_ha_size_ratio,5477735.0,1.137337,0.069114,0.719235,0.973866,1.351317,10.0,0.684371
d1_ha_ha_body_accel,5477735.0,-0.00064,-0.913236,-0.187962,0.001577,0.187377,0.86553,0.292059
d1_ha_ha_trend_score_5,5477735.0,0.097671,-1.0,-0.2,0.2,0.6,1.0,0.635214
d1_ha_ha_bull_power_5,5477735.0,0.300299,0.0,0.0,0.2,0.4,1.0,0.285161
d1_ha_ha_bear_power_5,5477735.0,0.233412,0.0,0.0,0.2,0.4,1.0,0.2566
d1_ha_ha_doji_freq_5,5477735.0,0.101417,0.0,0.0,0.0,0.2,1.0,0.13795
d1_ha_ha_motive_avg_5,5477735.0,0.450917,0.060411,0.364476,0.450444,0.537098,0.950112,0.12349
d1_ha_ha_trend_score_10,5477735.0,0.092127,-1.0,-0.2,0.2,0.4,1.0,0.483252
d1_ha_ha_bull_power_10,5477735.0,0.297964,0.0,0.1,0.3,0.4,1.0,0.21747
d1_ha_ha_bear_power_10,5477735.0,0.235467,0.0,0.1,0.2,0.4,1.0,0.192717
d1_ha_ha_doji_freq_10,5477735.0,0.101242,0.0,0.0,0.1,0.2,0.7,0.097734
d1_ha_ha_motive_avg_10,5477735.0,0.451071,0.104702,0.388878,0.450389,0.512655,0.803123,0.089647
d1_lrsi_lrsi,5477735.0,0.071443,-1.0,-0.734574,0.13197,0.947755,1.0,0.776498
d1_adx_adx,5477735.0,-0.424749,-3.729165,-1.954993,-0.799624,0.837188,4.875209,1.894021
d1_adx_plus_di,5477735.0,-0.260502,-4.00611,-1.592888,-0.408727,0.944236,4.739473,1.696943
d1_adx_minus_di,5477735.0,-0.424199,-4.034229,-1.689521,-0.576017,0.684517,4.882248,1.648835
spy_m5_rel_vol,5477735.0,-0.071383,-9.770148,-0.597585,-0.167213,0.361449,4.824339,0.822957
spy_m5_rel_cum_vol,5477735.0,0.03383,-1.497575,-0.305713,-0.049292,0.261956,3.108084,0.572997
spy_m5_chg_from_yest_close_pct,5477735.0,0.000287,-0.059471,-0.003577,0.001044,0.00528,0.097859,0.011456
spy_m5_chg_from_open_pct,5477735.0,0.000456,-0.059325,-0.002764,0.000786,0.003944,0.104734,0.008472
spy_m5_lrsi,5477735.0,0.1007,-1.0,-0.691092,0.20734,0.987959,1.0,0.77936
spy_m5_ha_color,5477735.0,0.050288,-1.0,-1.0,1.0,1.0,1.0,0.998735
spy_m5_ha_flat_bottom,5477735.0,-0.460296,-1.0,-1.0,-1.0,1.0,1.0,0.887766
spy_m5_ha_flat_top,5477735.0,-0.567734,-1.0,-1.0,-1.0,-1.0,1.0,0.823212
spy_m5_ha_body_pct,5477735.0,0.421178,0.000068,0.222268,0.452993,0.609467,0.981388,0.228723
spy_m5_ha_wick_upper_pct,5477735.0,0.291528,0.0,0.073056,0.339212,0.456886,0.720588,0.200383
spy_m5_ha_wick_lower_pct,5477735.0,0.287295,0.0,0.0,0.340906,0.478117,0.749693,0.220157
spy_m5_ha_doji,5477735.0,-0.768044,-1.0,-1.0,-1.0,-1.0,1.0,0.640398
spy_m5_ha_size_ratio,5477735.0,1.11209,0.141596,0.746835,0.970165,1.285714,10.0,0.666715
spy_m5_ha_body_accel,5477735.0,0.000028,-0.835969,-0.174936,0.002856,0.181284,0.925378,0.274299
spy_m5_ha_trend_score_6,5477735.0,0.050479,-1.0,-0.333333,0.0,0.666667,1.0,0.636828
spy_m5_ha_bull_power_6,5477735.0,0.269945,0.0,0.0,0.166667,0.5,1.0,0.268529
spy_m5_ha_bear_power_6,5477735.0,0.216044,0.0,0.0,0.166667,0.333333,1.0,0.241439
spy_m5_ha_doji_freq_6,5477735.0,0.115958,0.0,0.0,0.166667,0.166667,0.833333,0.135519
spy_m5_ha_motive_avg_6,5477735.0,0.42117,0.078243,0.338784,0.417309,0.499839,0.838984,0.116823
spy_m5_ha_trend_score_12,5477735.0,0.050778,-1.0,-0.333333,0.0,0.333333,1.0,0.485106
spy_m5_ha_bull_power_12,5477735.0,0.270058,0.0,0.083333,0.25,0.416667,1.0,0.201969
spy_m5_ha_bear_power_12,5477735.0,0.21598,0.0,0.083333,0.166667,0.333333,1.0,0.183453
spy_m5_ha_doji_freq_12,5477735.0,0.115952,0.0,0.083333,0.083333,0.166667,0.5,0.096431
spy_m5_ha_motive_avg_12,5477735.0,0.421197,0.184511,0.363491,0.419443,0.475569,0.735034,0.083579
spy_d1_ha_color,5477735.0,0.269316,-1.0,-1.0,1.0,1.0,1.0,0.963052
spy_d1_ha_flat_bottom,5477735.0,-0.231708,-1.0,-1.0,-1.0,1.0,1.0,0.972785
spy_d1_ha_flat_top,5477735.0,-0.627355,-1.0,-1.0,-1.0,-1.0,1.0,0.778733
spy_d1_ha_body_pct,5477735.0,0.490419,0.001497,0.240748,0.561917,0.702152,0.895106,0.256071
spy_d1_ha_wick_upper_pct,5477735.0,0.266153,0.0,0.079816,0.297848,0.420104,0.624586,0.182677
spy_d1_ha_wick_lower_pct,5477735.0,0.243427,0.0,0.0,0.27728,0.445803,0.6875,0.223785
spy_d1_ha_doji,5477735.0,-0.785258,-1.0,-1.0,-1.0,-1.0,1.0,0.619168
spy_d1_ha_size_ratio,5477735.0,1.093795,0.341572,0.71204,1.009932,1.309624,4.025608,0.51455
spy_d1_ha_body_accel,5477735.0,0.000415,-0.832619,-0.15716,0.004429,0.171736,0.779274,0.328595
spy_d1_ha_trend_score_5,5477735.0,0.249328,-1.0,-0.2,0.2,0.6,1.0,0.621062
spy_d1_ha_bull_power_5,5477735.0,0.376992,0.0,0.2,0.4,0.6,1.0,0.30476
spy_d1_ha_bear_power_5,5477735.0,0.192027,0.0,0.0,0.0,0.4,1.0,0.249611
spy_d1_ha_doji_freq_5,5477735.0,0.107379,0.0,0.0,0.0,0.2,0.4,0.122873
spy_d1_ha_motive_avg_5,5477735.0,0.49057,0.246182,0.40466,0.49112,0.561712,0.807041,0.122891
spy_d1_ha_trend_score_10,5477735.0,0.236481,-1.0,0.0,0.4,0.6,1.0,0.470627
spy_d1_ha_bull_power_10,5477735.0,0.371274,0.0,0.2,0.4,0.5,0.8,0.22747
spy_d1_ha_bear_power_10,5477735.0,0.19557,0.0,0.0,0.2,0.3,0.7,0.19212
spy_d1_ha_doji_freq_10,5477735.0,0.107385,0.0,0.0,0.1,0.2,0.3,0.087494
spy_d1_ha_motive_avg_10,5477735.0,0.491397,0.283192,0.438457,0.484898,0.545819,0.69544,0.080596
d1_natr,5477735.0,0.035888,0.002258,0.02123,0.028685,0.041681,0.625187,0.023987
natr_spy_d1_atr_14,5477735.0,0.016274,0.006966,0.010615,0.01317,0.018534,0.045297,0.009399
dist_m5_ma_ema_3,5477735.0,-0.000002,-0.128045,-0.000567,-0.000019,0.000544,0.271,0.002069
dist_m5_ma_ema_8,5477735.0,-0.000009,-0.200166,-0.001256,-0.000063,0.001172,0.423262,0.004427
dist_m5_ma_vwap,5477735.0,-0.000135,-0.169979,-0.004019,-0.000372,0.003463,0.277047,0.009125
dist_m5_lvl_yest_high,5477735.0,0.015873,-0.337877,-0.000875,0.010184,0.025327,1.244664,0.035033
dist_m5_lvl_yest_low,5477735.0,-0.016594,-0.452206,-0.028117,-0.013633,-0.002141,0.939227,0.032122
dist_m5_lvl_yest_close,5477735.0,0.000094,-0.36004,-0.01095,-0.000867,0.009301,1.031028,0.028551
dist_m5_lvl_hod,5477735.0,0.012996,0.0,0.003502,0.008057,0.016216,0.661371,0.016078
dist_m5_lvl_lod,5477735.0,-0.013511,-0.448015,-0.017163,-0.009495,-0.004527,0.0,0.01517
dist_m5_lvl_session_open,5477735.0,-0.000184,-0.304973,-0.0087,-0.000523,0.007784,0.653922,0.020562
dist_open_d1,5477735.0,-0.000326,-0.419108,-0.016601,-0.001872,0.013452,1.214962,0.037199
dist_high_d1,5477735.0,0.015873,-0.337877,-0.000875,0.010184,0.025327,1.244664,0.035033
dist_low_d1,5477735.0,-0.016594,-0.452206,-0.028117,-0.013633,-0.002141,0.939227,0.032122
dist_close_d1,5477735.0,0.000094,-0.36004,-0.01095,-0.000867,0.009301,1.031028,0.028551
dist_d1_trend_open,5477735.0,-0.000326,-0.419108,-0.016601,-0.001872,0.013452,1.214962,0.037199
dist_d1_trend_high,5477735.0,0.015873,-0.337877,-0.000875,0.010184,0.025327,1.244664,0.035033
dist_d1_trend_low,5477735.0,-0.016594,-0.452206,-0.028117,-0.013633,-0.002141,0.939227,0.032122
dist_d1_trend_close,5477735.0,0.000094,-0.36004,-0.01095,-0.000867,0.009301,1.031028,0.028551
dist_d1_trend_sma_20,5477735.0,0.000218,-0.553564,-0.039571,-0.006221,0.03069,1.343984,0.078442
dist_d1_trend_sma_50,5477735.0,0.004568,-0.773769,-0.060423,-0.006826,0.053374,1.586374,0.120021
dist_d1_trend_sma_100,5477735.0,0.011599,-0.866111,-0.070108,-0.003707,0.078435,1.862749,0.152883
dist_d1_trend_sma_200,5447721.0,-0.000294,-0.904064,-0.107926,-0.016152,0.087699,1.716262,0.195725
dist_d1_trend_ema_8,5477735.0,-0.000064,-0.435148,-0.022231,-0.003806,0.016398,1.339185,0.04722
dist_d1_trend_ema_21,5477735.0,0.00091,-0.514698,-0.034825,-0.005547,0.027549,1.155826,0.069969
dist_d1_trend_high_52w,5409420.0,0.314968,-0.305741,0.080936,0.194519,0.396387,6.330467,0.407027
dist_d1_trend_low_52w,5409420.0,-0.267607,-0.996465,-0.353093,-0.231038,-0.135071,0.563663,0.18549
dist_d1_trend_prev_day_high,5477735.0,0.015672,-0.41255,-0.006998,0.009291,0.029853,1.366851,0.047678
dist_d1_trend_prev_day_low,5477735.0,-0.016764,-0.495327,-0.03454,-0.015143,0.00181,1.047514,0.044068
dist_d1_trend_prev_week_high,5477735.0,0.040439,-0.557617,-0.014778,0.022706,0.073457,2.388618,0.103736
dist_d1_trend_prev_week_low,5477735.0,-0.0405,-0.669946,-0.081226,-0.038516,-0.000587,1.395489,0.087107
dist_d1_trend_prev_month_high,5477735.0,0.113791,-0.841112,-0.007404,0.072948,0.181505,3.627182,0.223537
dist_d1_trend_prev_month_low,5477735.0,-0.068249,-0.950023,-0.148277,-0.06724,0.013695,1.582413,0.16001
dist_spy_m5_close,5477735.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
dist_spy_m5_yest_high,5477735.0,0.006099,-0.036946,-0.001196,0.00312,0.010973,0.087632,0.013391
dist_spy_m5_yest_low,5477735.0,-0.007926,-0.102656,-0.013425,-0.006631,-0.001492,0.061412,0.013832
dist_spy_m5_yest_close,5477735.0,-0.000155,-0.089136,-0.005252,-0.001043,0.00359,0.063231,0.011481
dist_spy_m5_hod,5477735.0,0.004476,0.0,0.000843,0.002272,0.00574,0.069402,0.006301
dist_spy_m5_lod,5477735.0,-0.005412,-0.09552,-0.006772,-0.003909,-0.001875,0.0,0.006621
dist_spy_m5_session_open,5477735.0,-0.000386,-0.094805,-0.003929,-0.000786,0.002771,0.063067,0.008305
dist_spy_m5_ema_8,5477735.0,-0.000022,-0.031858,-0.000644,-0.000086,0.000528,0.032498,0.001968
dist_spy_m5_vwap,5477735.0,-0.000304,-0.049531,-0.002112,-0.000495,0.001193,0.037812,0.004239
dist_spy_d1_close,5477735.0,-0.00015,-0.089136,-0.005127,-0.000936,0.003494,0.063231,0.011369
dist_spy_d1_sma_20,5477735.0,-0.002586,-0.06712,-0.022021,-0.011142,0.016574,0.15657,0.032991
dist_spy_d1_sma_50,5477735.0,-0.003306,-0.06941,-0.050124,-0.010057,0.029829,0.205354,0.051502
dist_spy_d1_sma_200,5477735.0,-0.019549,-0.084567,-0.063113,-0.033158,0.014356,0.188103,0.052134
dist_spy_d1_ema_8,5477735.0,-0.001222,-0.039904,-0.01202,-0.005353,0.006033,0.129661,0.019501
dist_spy_d1_ema_21,5477735.0,-0.002211,-0.056557,-0.022247,-0.010368,0.014154,0.159286,0.029925
dist_spy_d1_high_52w,5477735.0,0.052301,-0.009039,0.01125,0.033679,0.085555,0.268314,0.052435
dist_spy_d1_low_52w,5477735.0,-0.170287,-0.244241,-0.202649,-0.186632,-0.13468,0.021427,0.04723
dist_spy_d1_prev_day_high,5477735.0,0.005673,-0.042823,-0.005047,0.001958,0.013637,0.13334,0.018576
dist_spy_d1_prev_day_low,5477735.0,-0.008397,-0.116158,-0.01592,-0.007632,0.000481,0.109928,0.019406
target_reg_5m_logret,5477237.0,0.000008,-0.431863,-0.000958,0.0,0.000977,0.292853,0.003565
target_cls_5m,5477735.0,1.00143,0.0,1.0,1.0,1.0,2.0,0.530903
target_reg_30m_logret,5474747.0,0.000049,-0.619356,-0.00238,0.000082,0.0025,0.371462,0.008686
target_cls_30m,5477735.0,1.003719,0.0,1.0,1.0,1.0,2.0,0.540624
target_reg_1h_logret,5471759.0,0.000096,-0.669727,-0.003462,0.000169,0.003725,0.369997,0.012221
target_cls_1h,5477735.0,1.005654,0.0,1.0,1.0,1.0,2.0,0.556535
target_reg_2h_logret,5465783.0,0.000193,-0.718244,-0.005247,0.000338,0.005774,0.455687,0.017327
target_cls_2h,5477735.0,1.009536,0.0,1.0,1.0,1.0,2.0,0.583895
target_reg_4h_logret,5453831.0,0.000389,-0.705437,-0.008,0.00073,0.009282,0.520152,0.024332
target_cls_4h,5477735.0,1.020136,0.0,1.0,1.0,1.0,2.0,0.615566
target_reg_1d_logret,5438891.0,0.000642,-0.692956,-0.01079,0.00123,0.013169,0.499735,0.030523
target_cls_1d,5477735.0,1.030801,0.0,1.0,1.0,1.0,2.0,0.638664
target_reg_3d_logret,5361203.0,0.001694,-1.112917,-0.018668,0.003741,0.024936,0.794529,0.052481
target_cls_3d,5477735.0,1.039545,0.0,1.0,1.0,1.0,2.0,0.649094
target_reg_5d_logret,5283515.0,0.002763,-1.23497,-0.024535,0.005592,0.033873,0.960638,0.066639
target_cls_5d,5477735.0,1.041737,0.0,1.0,1.0,1.0,2.0,0.652771
target_reg_10d_logret,5089295.0,0.005505,-0.822248,-0.034604,0.00941,0.051675,1.003302,0.092859
target_cls_10d,5477735.0,1.048108,0.0,1.0,1.0,1.0,2.0,0.653555

In [8]:
len(universe['ticker'].unique())

498

In [10]:
universe.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5477735 entries, 0 to 5477734
Data columns (total 205 columns):
 #    Column                          Dtype
---   ------                          -----
 0    timestamp                       datetime64[us]
 1    m5_mom_lrsi                     float64
 2    m5_mom_tsi                      float64
 3    m5_mom_squeeze_on               float32
 4    m5_vol_rel_vol                  float32
 5    m5_vol_rel_cum_vol              float32
 6    m5_ha_ha_color                  float32
 7    m5_ha_ha_flat_bottom            float32
 8    m5_ha_ha_flat_top               float32
 9    m5_ha_ha_body_pct               float32
 10   m5_ha_ha_wick_upper_pct         float32
 11   m5_ha_ha_wick_lower_pct         float32
 12   m5_ha_ha_doji                   float32
 13   m5_ha_ha_size_ratio             float32
 14   m5_ha_ha_body_accel             float32
 15   m5_ha_ha_trend_score_6          float32
 16   m5_ha_ha_bull_power_6           float32
 17   m5_ha_ha_bear_power_6           float32
 18   m5_ha_ha_doji_freq_6            float32
 19   m5_ha_ha_motive_avg_6           float32
 20   m5_ha_ha_trend_score_12         float32
 21   m5_ha_ha_bull_power_12          float32
 22   m5_ha_ha_bear_power_12          float32
 23   m5_ha_ha_doji_freq_12           float32
 24   m5_ha_ha_motive_avg_12          float32
 25   m5_rrs_mom_5                    float32
 26   m5_rrs_rrs_spy_5                float32
 27   m5_rrs_rrs_spy_5_sma            float32
 28   m5_rrs_vrrs_spy_5               float32
 29   m5_rrs_rrs_sec_5                float32
 30   m5_rrs_rrs_sec_5_sma            float32
 31   m5_rrs_vrrs_sec_5               float32
 32   m5_rrs_mom_12                   float32
 33   m5_rrs_rrs_spy_12               float32
 34   m5_rrs_rrs_spy_12_sma           float32
 35   m5_rrs_vrrs_spy_12              float32
 36   m5_rrs_rrs_sec_12               float32
 37   m5_rrs_rrs_sec_12_sma           float32
 38   m5_rrs_vrrs_sec_12              float32
 39   m5_rrs_mom_25                   float32
 40   m5_rrs_rrs_spy_25               float32
 41   m5_rrs_rrs_spy_25_sma           float32
 42   m5_rrs_vrrs_spy_25              float32
 43   m5_rrs_rrs_sec_25               float32
 44   m5_rrs_rrs_sec_25_sma           float32
 45   m5_rrs_vrrs_sec_25              float32
 46   m5_time_time_weekday            float32
 47   m5_time_time_month_sin          float32
 48   m5_time_time_month_cos          float32
 49   m5_time_time_day_sin            float32
 50   m5_time_time_day_cos            float32
 51   m5_time_time_mkt_open_min       float32
 52   m5_time_time_mkt_close_min      float32
 53   d1_rrs_mom_5                    float32
 54   d1_rrs_rrs_spy_5                float32
 55   d1_rrs_rrs_spy_5_sma            float32
 56   d1_rrs_rrs_sec_5                float32
 57   d1_rrs_rrs_sec_5_sma            float32
 58   d1_rrs_mom_12                   float32
 59   d1_rrs_rrs_spy_12               float32
 60   d1_rrs_rrs_spy_12_sma           float32
 61   d1_rrs_rrs_sec_12               float32
 62   d1_rrs_rrs_sec_12_sma           float32
 63   d1_rrs_mom_25                   float32
 64   d1_rrs_rrs_spy_25               float32
 65   d1_rrs_rrs_spy_25_sma           float32
 66   d1_rrs_rrs_sec_25               float32
 67   d1_rrs_rrs_sec_25_sma           float32
 68   d1_ha_ha_color                  float32
 69   d1_ha_ha_flat_bottom            float32
 70   d1_ha_ha_flat_top               float32
 71   d1_ha_ha_body_pct               float32
 72   d1_ha_ha_wick_upper_pct         float32
 73   d1_ha_ha_wick_lower_pct         float32
 74   d1_ha_ha_doji                   float32
 75   d1_ha_ha_size_ratio             float32
 76   d1_ha_ha_body_accel             float32
 77   d1_ha_ha_trend_score_5          float32
 78   d1_ha_ha_bull_power_5           float32
 79   d1_ha_ha_bear_power_5           float32
 80   d1_ha_ha_doji_freq_5            float32
 81   d1_ha_ha_motive_avg_5           float32
 82   d1_ha_ha_trend_score_10         float32
 83   d1_ha_ha_bull_power_10          float32
 84   d1_ha_ha_bear_power_10          float32
 85   d1_ha_ha_doji_freq_10           float32
 86   d1_ha_ha_motive_avg_10          float32
 87   d1_lrsi_lrsi                    float64
 88   d1_adx_adx                      float32
 89   d1_adx_plus_di                  float32
 90   d1_adx_minus_di                 float32
 91   spy_m5_rel_vol                  float32
 92   spy_m5_rel_cum_vol              float32
 93   spy_m5_chg_from_yest_close_pct  float64
 94   spy_m5_chg_from_open_pct        float64
 95   spy_m5_lrsi                     float64
 96   spy_m5_ha_color                 float32
 97   spy_m5_ha_flat_bottom           float32
 98   spy_m5_ha_flat_top              float32
 99   spy_m5_ha_body_pct              float32
 100  spy_m5_ha_wick_upper_pct        float32
 101  spy_m5_ha_wick_lower_pct        float32
 102  spy_m5_ha_doji                  float32
 103  spy_m5_ha_size_ratio            float32
 104  spy_m5_ha_body_accel            float32
 105  spy_m5_ha_trend_score_6         float32
 106  spy_m5_ha_bull_power_6          float32
 107  spy_m5_ha_bear_power_6          float32
 108  spy_m5_ha_doji_freq_6           float32
 109  spy_m5_ha_motive_avg_6          float32
 110  spy_m5_ha_trend_score_12        float32
 111  spy_m5_ha_bull_power_12         float32
 112  spy_m5_ha_bear_power_12         float32
 113  spy_m5_ha_doji_freq_12          float32
 114  spy_m5_ha_motive_avg_12         float32
 115  spy_d1_ha_color                 float32
 116  spy_d1_ha_flat_bottom           float32
 117  spy_d1_ha_flat_top              float32
 118  spy_d1_ha_body_pct              float32
 119  spy_d1_ha_wick_upper_pct        float32
 120  spy_d1_ha_wick_lower_pct        float32
 121  spy_d1_ha_doji                  float32
 122  spy_d1_ha_size_ratio            float32
 123  spy_d1_ha_body_accel            float32
 124  spy_d1_ha_trend_score_5         float32
 125  spy_d1_ha_bull_power_5          float32
 126  spy_d1_ha_bear_power_5          float32
 127  spy_d1_ha_doji_freq_5           float32
 128  spy_d1_ha_motive_avg_5          float32
 129  spy_d1_ha_trend_score_10        float32
 130  spy_d1_ha_bull_power_10         float32
 131  spy_d1_ha_bear_power_10         float32
 132  spy_d1_ha_doji_freq_10          float32
 133  spy_d1_ha_motive_avg_10         float32
 134  d1_natr                         float32
 135  natr_spy_d1_atr_14              float32
 136  dist_m5_ma_ema_3                float32
 137  dist_m5_ma_ema_8                float32
 138  dist_m5_ma_vwap                 float32
 139  dist_m5_lvl_yest_high           float32
 140  dist_m5_lvl_yest_low            float32
 141  dist_m5_lvl_yest_close          float32
 142  dist_m5_lvl_hod                 float32
 143  dist_m5_lvl_lod                 float32
 144  dist_m5_lvl_session_open        float32
 145  dist_open_d1                    float32
 146  dist_high_d1                    float32
 147  dist_low_d1                     float32
 148  dist_close_d1                   float32
 149  dist_d1_trend_open              float32
 150  dist_d1_trend_high              float32
 151  dist_d1_trend_low               float32
 152  dist_d1_trend_close             float32
 153  dist_d1_trend_sma_20            float32
 154  dist_d1_trend_sma_50            float32
 155  dist_d1_trend_sma_100           float32
 156  dist_d1_trend_sma_200           float32
 157  dist_d1_trend_ema_8             float32
 158  dist_d1_trend_ema_21            float32
 159  dist_d1_trend_high_52w          float32
 160  dist_d1_trend_low_52w           float32
 161  dist_d1_trend_prev_day_high     float32
 162  dist_d1_trend_prev_day_low      float32
 163  dist_d1_trend_prev_week_high    float32
 164  dist_d1_trend_prev_week_low     float32
 165  dist_d1_trend_prev_month_high   float32
 166  dist_d1_trend_prev_month_low    float32
 167  dist_spy_m5_close               float32
 168  dist_spy_m5_yest_high           float32
 169  dist_spy_m5_yest_low            float32
 170  dist_spy_m5_yest_close          float32
 171  dist_spy_m5_hod                 float32
 172  dist_spy_m5_lod                 float32
 173  dist_spy_m5_session_open        float32
 174  dist_spy_m5_ema_8               float32
 175  dist_spy_m5_vwap                float32
 176  dist_spy_d1_close               float32
 177  dist_spy_d1_sma_20              float32
 178  dist_spy_d1_sma_50              float32
 179  dist_spy_d1_sma_200             float32
 180  dist_spy_d1_ema_8               float32
 181  dist_spy_d1_ema_21              float32
 182  dist_spy_d1_high_52w            float32
 183  dist_spy_d1_low_52w             float32
 184  dist_spy_d1_prev_day_high       float32
 185  dist_spy_d1_prev_day_low        float32
 186  target_reg_5m_logret            float32
 187  target_cls_5m                   int8
 188  target_reg_30m_logret           float32
 189  target_cls_30m                  int8
 190  target_reg_1h_logret            float32
 191  target_cls_1h                   int8
 192  target_reg_2h_logret            float32
 193  target_cls_2h                   int8
 194  target_reg_4h_logret            float32
 195  target_cls_4h                   int8
 196  target_reg_1d_logret            float32
 197  target_cls_1d                   int8
 198  target_reg_3d_logret            float32
 199  target_cls_3d                   int8
 200  target_reg_5d_logret            float32
 201  target_cls_5d                   int8
 202  target_reg_10d_logret           float32
 203  target_cls_10d                  int8
 204  ticker                          object
dtypes: datetime64[us](1), float32(188), float64(6), int8(9), object(1)
memory usage: 4.2+ GB